# Generated by Django 5.1.4 on 2026-08-03 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_assettransfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="depreciation_method",
            field=models.CharField(
                choices=[
                    ("straight_line", "Straight Line"),
                    ("reducing_balance", "Reducing Balance"),
                    ("no_depreciation", "No Depreciation"),
                ],
                db_index=True,
                default="straight_line",
                max_length=30,
                verbose_name="depreciation method",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="salvage_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated residual value at end of useful life",
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="salvage value",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="useful_life_years",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Expected useful life in years",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="useful life years",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="warranty_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="warranty start date"
            ),
        ),
    ]
