# Generated by Django 5.1.4 on 2026-08-06 05:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_asset_depreciation_method_asset_salvage_value_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetLifecycleEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("status_changed", "Status Changed"),
                            ("condition_changed", "Condition Changed"),
                            ("transferred", "Transferred"),
                            ("owner_changed", "Owner Changed"),
                            ("location_changed", "Location Changed"),
                            ("disposed", "Disposed"),
                            ("retired", "Retired"),
                            ("maintenance_scheduled", "Maintenance Scheduled"),
                            ("maintenance_completed", "Maintenance Completed"),
                            ("depreciation_updated", "Depreciation Updated"),
                            ("value_updated", "Value Updated"),
                            ("qr_generated", "QR Generated"),
                            ("scanned", "Scanned"),
                            ("amc_updated", "AMC Updated"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="event type",
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="actor name"
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="old value"
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="new value"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="message"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="occurred at"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_lifecycle_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle_events",
                        to="assets.asset",
                        verbose_name="asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "asset lifecycle event",
                "verbose_name_plural": "asset lifecycle events",
                "db_table": "asset_lifecycle_events",
                "ordering": ["-occurred_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["asset", "event_type"],
                        name="asset_lifec_asset_i_0561e9_idx",
                    ),
                    models.Index(
                        fields=["occurred_at"], name="asset_lifec_occurre_f5f7bc_idx"
                    ),
                ],
            },
        ),
    ]
