# Generated by Django 5.1.4 on 2026-08-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0005_assetlifecycleevent"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="asset",
            name="check_quantity_positive",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="quantity",
        ),
    ]
