# Generated by Django 5.1.4 on 2026-07-01 08:48

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "asset_code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="asset code",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="barcode",
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="QR code",
                    ),
                ),
                (
                    "rfid",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="RFID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="serial number",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="subcategory",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="manufacturer",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="model"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="department"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="location"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="purchase date"
                    ),
                ),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="purchase cost",
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="PO number"
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="vendor"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="invoice number",
                    ),
                ),
                (
                    "warranty_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="warranty expiry"
                    ),
                ),
                (
                    "warranty_provider",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="warranty provider",
                    ),
                ),
                (
                    "warranty_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="warranty notes"
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="current value",
                    ),
                ),
                (
                    "depreciation_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual depreciation rate in percentage",
                        max_digits=5,
                        null=True,
                        verbose_name="depreciation rate",
                    ),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="accumulated depreciation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("disposed", "Disposed"),
                            ("lost", "Lost"),
                            ("damaged", "Damaged"),
                            ("under_maintenance", "Under Maintenance"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=30,
                        verbose_name="status",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                        ],
                        db_index=True,
                        default="good",
                        max_length=20,
                        verbose_name="condition",
                    ),
                ),
                (
                    "amc_enabled",
                    models.BooleanField(default=False, verbose_name="AMC enabled"),
                ),
                (
                    "amc_provider",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="AMC provider",
                    ),
                ),
                (
                    "amc_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="AMC start date"
                    ),
                ),
                (
                    "amc_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="AMC end date"
                    ),
                ),
                (
                    "amc_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="AMC cost",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="expiry date"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="asset_images/",
                        verbose_name="image",
                    ),
                ),
                (
                    "documents",
                    models.JSONField(
                        blank=True, default=list, null=True, verbose_name="documents"
                    ),
                ),
            ],
            options={
                "verbose_name": "asset",
                "verbose_name_plural": "assets",
                "db_table": "assets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="asset_attachments/", verbose_name="file"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="file name"),
                ),
                (
                    "file_type",
                    models.CharField(max_length=100, verbose_name="file type"),
                ),
                ("file_size", models.IntegerField(verbose_name="file size")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "asset attachment",
                "verbose_name_plural": "asset attachments",
                "db_table": "asset_attachments",
                "ordering": ["-created_at"],
            },
        ),
    ]
