# Generated by Django 5.1.4 on 2026-07-01 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("categories", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="categories.category",
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="item_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="categories.itemtype",
                verbose_name="item type",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_assets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="properties.property",
                verbose_name="property",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="assetattachment",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="assets.asset",
                verbose_name="asset",
            ),
        ),
        migrations.AddField(
            model_name="assetattachment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="assetattachment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="assetattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_attachments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="uploaded by",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["asset_code"], name="assets_asset_c_4e968f_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["barcode"], name="assets_barcode_f832ae_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["qr_code"], name="assets_qr_code_ea6215_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["rfid"], name="assets_rfid_81eb98_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["serial_number"], name="assets_serial__240171_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["status"], name="assets_status_326766_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["condition"], name="assets_conditi_21262e_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["property"], name="assets_propert_5af3fb_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["department"], name="assets_departm_4e9c7b_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["category"], name="assets_categor_840335_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["item_type"], name="assets_item_ty_8332d3_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["owner"], name="assets_owner_i_b9eeda_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["is_active"], name="assets_is_acti_0f03da_idx"),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="check_quantity_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="assetattachment",
            index=models.Index(fields=["asset"], name="asset_attac_asset_i_f4f3ea_idx"),
        ),
    ]
