# Generated by Django 5.1.4 on 2026-07-27 08:23

from django.db import migrations


def strip_emp_prefix(apps, schema_editor):
    Employee = apps.get_model("employees", "Employee")
    HouseApplication = apps.get_model("houses", "HouseApplication")

    # Update all employees: strip EMP- prefix
    for emp in Employee.objects.all():
        if emp.employee_id and emp.employee_id.startswith("EMP-"):
            emp.employee_id = emp.employee_id.replace("EMP-", "")
            emp.save(update_fields=["employee_id"])

    # Update all house applications referencing the old IDs
    for app in HouseApplication.objects.all():
        if app.employee_id and app.employee_id.startswith("EMP-"):
            app.employee_id = app.employee_id.replace("EMP-", "")
            app.save(update_fields=["employee_id"])


def reverse_strip(apps, schema_editor):
    Employee = apps.get_model("employees", "Employee")
    HouseApplication = apps.get_model("houses", "HouseApplication")

    for emp in Employee.objects.all():
        if emp.employee_id and not emp.employee_id.startswith("EMP-"):
            emp.employee_id = f"EMP-{emp.employee_id}"
            emp.save(update_fields=["employee_id"])

    for app in HouseApplication.objects.all():
        if app.employee_id and not app.employee_id.startswith("EMP-"):
            app.employee_id = f"EMP-{app.employee_id}"
            app.save(update_fields=["employee_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_add_job_type"),
        ("houses", "0009_add_job_type"),
    ]

    operations = [
        migrations.RunPython(strip_emp_prefix, reverse_strip),
    ]
