# Generated by Django 5.1.4 on 2026-07-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="type",
            field=models.CharField(
                choices=[
                    ("office", "Office"),
                    ("storage", "Storage"),
                    ("manufacturing", "Manufacturing"),
                    ("site_office", "Site Office"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="office",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
