# Generated by Django 5.1.4 on 2026-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="damaged_bulb",
            field=models.BooleanField(default=False, verbose_name="damaged bulb"),
        ),
        migrations.AddField(
            model_name="house",
            name="damaged_door",
            field=models.BooleanField(default=False, verbose_name="damaged door"),
        ),
        migrations.AddField(
            model_name="house",
            name="damaged_switch",
            field=models.BooleanField(default=False, verbose_name="damaged switch"),
        ),
        migrations.AddField(
            model_name="house",
            name="damaged_walls",
            field=models.BooleanField(default=False, verbose_name="damaged walls"),
        ),
        migrations.AddField(
            model_name="house",
            name="damaged_water",
            field=models.BooleanField(default=False, verbose_name="damaged water"),
        ),
        migrations.AddField(
            model_name="house",
            name="damaged_windows",
            field=models.BooleanField(default=False, verbose_name="damaged windows"),
        ),
        migrations.AlterField(
            model_name="house",
            name="house_type",
            field=models.CharField(
                choices=[
                    ("Staff", "Staff"),
                    ("A", "Type A"),
                    ("B", "Type B"),
                    ("C", "Type C"),
                    ("D", "Type D"),
                    ("E", "Type E (Barrack)"),
                ],
                db_index=True,
                default="Staff",
                max_length=10,
                verbose_name="type",
            ),
        ),
    ]
