# Generated by Django 5.1.4 on 2026-07-08 06:49

import django.db.models.deletion
import houses.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_house_damaged_bulb_house_damaged_door_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "application_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="application number",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(max_length=50, verbose_name="employee ID"),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=255, verbose_name="employee name"),
                ),
                (
                    "national_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="national ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                        verbose_name="gender",
                    ),
                ),
                (
                    "job_position",
                    models.CharField(max_length=255, verbose_name="job position"),
                ),
                (
                    "job_grade",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="job grade"
                    ),
                ),
                (
                    "years_of_service",
                    models.IntegerField(default=0, verbose_name="years of service"),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                        ],
                        default="Single",
                        max_length=20,
                        verbose_name="marital status",
                    ),
                ),
                (
                    "has_disability",
                    models.BooleanField(default=False, verbose_name="has disability"),
                ),
                (
                    "family_size",
                    models.PositiveIntegerField(default=1, verbose_name="family size"),
                ),
                (
                    "number_of_children",
                    models.PositiveIntegerField(
                        default=0, verbose_name="number of children"
                    ),
                ),
                (
                    "requested_house_category",
                    models.CharField(
                        choices=[
                            ("Staff", "Staff"),
                            ("A", "Type A"),
                            ("B", "Type B"),
                            ("C", "Type C"),
                            ("D", "Type D"),
                            ("E", "Type E (Barrack)"),
                        ],
                        default="Staff",
                        max_length=10,
                        verbose_name="requested house category",
                    ),
                ),
                (
                    "reason_for_request",
                    models.TextField(blank=True, verbose_name="reason for request"),
                ),
                (
                    "preferred_location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="preferred location"
                    ),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=houses.models.application_document_path,
                        verbose_name="supporting document",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Submitted", "Submitted"),
                            ("Under Review", "Under Review"),
                            ("Verified", "Verified"),
                            ("Waiting for Allocation", "Waiting for Allocation"),
                            ("Allocated", "Allocated"),
                            ("Rejected", "Rejected"),
                            ("Returned", "Returned"),
                        ],
                        db_index=True,
                        default="Draft",
                        max_length=30,
                        verbose_name="status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="submitted at"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reviewed at"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="rejection reason"),
                ),
                (
                    "returned_reason",
                    models.TextField(blank=True, verbose_name="returned reason"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="requester",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewed by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "house application",
                "verbose_name_plural": "house applications",
                "db_table": "house_applications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["application_no"], name="house_appli_applica_a24700_idx"
                    ),
                    models.Index(
                        fields=["national_id"], name="house_appli_nationa_f88202_idx"
                    ),
                    models.Index(
                        fields=["status"], name="house_appli_status_de810f_idx"
                    ),
                    models.Index(
                        fields=["requester"], name="house_appli_request_08fd1d_idx"
                    ),
                ],
            },
        ),
    ]
