# Generated by Django 5.1.4 on 2026-07-21 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0004_convert_legacy_house_ids"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseholdItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "item_name",
                    models.CharField(
                        help_text="Name of the item — e.g. Bed, Chair, Table, Locker",
                        max_length=255,
                        verbose_name="item name",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Furniture", "Furniture"),
                            ("Appliance", "Appliance"),
                            ("Electronics", "Electronics"),
                            ("Kitchen", "Kitchen"),
                            ("Bedroom", "Bedroom"),
                            ("Bathroom", "Bathroom"),
                            ("Lighting", "Lighting"),
                            ("Security", "Security"),
                            ("Other", "Other"),
                        ],
                        default="Furniture",
                        max_length=50,
                        verbose_name="category",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("Good", "Good"),
                            ("Fair", "Fair"),
                            ("Poor", "Poor"),
                            ("Damaged", "Damaged"),
                            ("Needs Replacement", "Needs Replacement"),
                        ],
                        default="Good",
                        max_length=50,
                        verbose_name="condition",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many of this item are in the house",
                        verbose_name="quantity",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="brand"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="model"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="serial number",
                    ),
                ),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="purchase cost",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="notes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_items",
                        to="houses.house",
                        verbose_name="house",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "household item",
                "verbose_name_plural": "household items",
                "db_table": "household_items",
                "ordering": ["item_name"],
                "indexes": [
                    models.Index(
                        fields=["house", "item_name"],
                        name="household_i_house_i_f9fa3f_idx",
                    ),
                    models.Index(
                        fields=["category"], name="household_i_categor_ff0823_idx"
                    ),
                    models.Index(
                        fields=["condition"], name="household_i_conditi_c4d706_idx"
                    ),
                ],
            },
        ),
    ]
