# Generated by Django 5.1.4 on 2026-07-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0005_add_household_item_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HouseholdItem",
        ),
    ]
