# Generated by Django 5.1.4 on 2026-07-25 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_add_marital_status"),
        ("houses", "0007_house_inside_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="houseapplication",
            name="emp_record",
            field=models.ForeignKey(
                blank=True,
                help_text="Must reference a valid, active employee record.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="house_applications",
                to="employees.employee",
                verbose_name="employee record",
            ),
        ),
    ]
