# Generated by Django 5.1.4 on 2026-07-01 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="title"
                    ),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("asset", "Asset"),
                            ("approval", "Approval"),
                            ("ticket", "Ticket"),
                            ("audit", "Audit"),
                            ("report", "Report"),
                            ("qr", "QR Code"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="read"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="user name"
                    ),
                ),
                (
                    "action_url",
                    models.URLField(blank=True, null=True, verbose_name="action URL"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="notificatio_user_id_e78525_idx"
                    ),
                    models.Index(fields=["read"], name="notificatio_read_50f6ce_idx"),
                    models.Index(fields=["type"], name="notificatio_type_8a8a78_idx"),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_e4c995_idx"
                    ),
                ],
            },
        ),
    ]
