# Generated by Django 5.1.4 on 2026-07-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("asset", "Asset"),
                    ("property", "Property"),
                    ("house", "House"),
                    ("newsletter", "Newsletter"),
                    ("allocation", "Allocation"),
                    ("license", "License"),
                    ("department", "Department"),
                    ("scan", "Scan"),
                    ("user", "User"),
                    ("setting", "Setting"),
                    ("approval", "Approval"),
                    ("ticket", "Ticket"),
                    ("audit", "Audit"),
                    ("report", "Report"),
                    ("qr", "QR Code"),
                ],
                db_index=True,
                default="system",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
