# Generated by Django 5.1.4 on 2026-07-01 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditassignment",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assigned to",
            ),
        ),
        migrations.AddField(
            model_name="auditassignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="auditassignment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="auditincharge",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="auditincharge",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="auditincharge",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_incharges",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="auditreport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="auditreport",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_audit_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="generated by",
            ),
        ),
        migrations.AddField(
            model_name="auditreport",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="auditreview",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="audit.auditassignment",
                verbose_name="assignment",
            ),
        ),
        migrations.AddField(
            model_name="auditreview",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="auditreview",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="reviewer",
            ),
        ),
        migrations.AddField(
            model_name="auditreview",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="auditscan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="auditscan",
            name="scanned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_scans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="scanned by",
            ),
        ),
        migrations.AddField(
            model_name="auditscan",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="auditsession",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="auditsession",
            name="initiated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_audits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="initiated by",
            ),
        ),
        migrations.AddField(
            model_name="auditsession",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_sessions",
                to="properties.property",
                verbose_name="property",
            ),
        ),
        migrations.AddField(
            model_name="auditsession",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="auditscan",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scans",
                to="audit.auditsession",
                verbose_name="session",
            ),
        ),
        migrations.AddField(
            model_name="auditreport",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="audit.auditsession",
                verbose_name="session",
            ),
        ),
        migrations.AddField(
            model_name="auditincharge",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incharges",
                to="audit.auditsession",
                verbose_name="session",
            ),
        ),
        migrations.AddField(
            model_name="auditassignment",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="audit.auditsession",
                verbose_name="session",
            ),
        ),
        migrations.AddIndex(
            model_name="auditreview",
            index=models.Index(
                fields=["assignment"], name="audit_revie_assignm_342e33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditreview",
            index=models.Index(
                fields=["reviewer"], name="audit_revie_reviewe_578b79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditsession",
            index=models.Index(
                fields=["property"], name="audit_sessi_propert_f8a854_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditsession",
            index=models.Index(fields=["status"], name="audit_sessi_status_90caa9_idx"),
        ),
        migrations.AddIndex(
            model_name="auditsession",
            index=models.Index(
                fields=["scheduled_date"], name="audit_sessi_schedul_31197a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditscan",
            index=models.Index(
                fields=["session"], name="audit_scans_session_c6af19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditscan",
            index=models.Index(
                fields=["asset_id"], name="audit_scans_asset_i_80b6d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditscan",
            index=models.Index(
                fields=["scanned_by"], name="audit_scans_scanned_f99adc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditscan",
            index=models.Index(
                fields=["scanned_at"], name="audit_scans_scanned_7ebb30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditreport",
            index=models.Index(
                fields=["session"], name="audit_repor_session_8c2ac3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditincharge",
            index=models.Index(
                fields=["session"], name="audit_incha_session_6560f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditincharge",
            index=models.Index(fields=["user"], name="audit_incha_user_id_98ff4c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="auditincharge",
            unique_together={("session", "user")},
        ),
        migrations.AddIndex(
            model_name="auditassignment",
            index=models.Index(
                fields=["session"], name="audit_assig_session_771d51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditassignment",
            index=models.Index(
                fields=["department"], name="audit_assig_departm_bc6eb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditassignment",
            index=models.Index(
                fields=["assigned_to"], name="audit_assig_assigne_c9c8ed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="auditassignment",
            unique_together={("session", "department")},
        ),
    ]
