# Generated by Django 5.1.4 on 2026-07-01 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("asset_request", "Asset Request"),
                            ("transfer_request", "Transfer Request"),
                            ("maintenance_request", "Maintenance Request"),
                            ("purchase_request", "Purchase Request"),
                            ("disposal_request", "Disposal Request"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="request type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="title"
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "requester_department",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="requester department",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "decision",
                    models.TextField(blank=True, null=True, verbose_name="decision"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="decided at"
                    ),
                ),
                (
                    "forwarded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="forwarded at"
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="request data"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to="assets.asset",
                        verbose_name="asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "current_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="current approver",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="decided by",
                    ),
                ),
                (
                    "forwarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forwarded_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="forwarded by",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="requester",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "approval request",
                "verbose_name_plural": "approval requests",
                "db_table": "approval_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("forwarded", "Forwarded"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("comment", "Comment"),
                        ],
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="actor name"
                    ),
                ),
                (
                    "actor_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="actor email",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="old status"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="new status"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="requests.approvalrequest",
                        verbose_name="approval",
                    ),
                ),
            ],
            options={
                "verbose_name": "approval event",
                "verbose_name_plural": "approval events",
                "db_table": "approval_events",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["request_type"], name="approval_re_request_7cdb83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(fields=["status"], name="approval_re_status_293063_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["requester"], name="approval_re_request_55eccf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(
                fields=["current_approver"], name="approval_re_current_718377_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrequest",
            index=models.Index(fields=["asset"], name="approval_re_asset_i_903de7_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalevent",
            index=models.Index(
                fields=["approval"], name="approval_ev_approva_8fc835_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalevent",
            index=models.Index(fields=["action"], name="approval_ev_action_c7bc99_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalevent",
            index=models.Index(
                fields=["created_at"], name="approval_ev_created_2b7808_idx"
            ),
        ),
    ]
