# Generated by Django 5.1.4 on 2026-07-06 07:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("key", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=200)),
                ("hue", models.CharField(default="blue", max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NewsletterPost",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=500)),
                ("body", models.TextField()),
                ("author", models.CharField(blank=True, max_length=200, null=True)),
                ("published", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="newsletter.newslettercategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="newslettercategory",
            index=models.Index(
                fields=["created_at"], name="newsletter__created_accb66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newslettercategory",
            index=models.Index(
                fields=["updated_at"], name="newsletter__updated_1fe53c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newslettercategory",
            index=models.Index(
                fields=["is_active"], name="newsletter__is_acti_767896_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsletterpost",
            index=models.Index(
                fields=["created_at"], name="newsletter__created_222857_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsletterpost",
            index=models.Index(
                fields=["updated_at"], name="newsletter__updated_491f66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsletterpost",
            index=models.Index(
                fields=["is_active"], name="newsletter__is_acti_8bcc1f_idx"
            ),
        ),
    ]
