# Generated by Django 5.1.4 on 2026-07-01 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset Report"),
                            ("maintenance", "Maintenance Report"),
                            ("audit", "Audit Report"),
                            ("approval", "Approval Report"),
                            ("user", "User Report"),
                            ("property", "Property Report"),
                            ("department", "Department Report"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        default="pdf",
                        max_length=10,
                        verbose_name="format",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "date_from",
                    models.DateField(blank=True, null=True, verbose_name="date from"),
                ),
                (
                    "date_to",
                    models.DateField(blank=True, null=True, verbose_name="date to"),
                ),
                (
                    "file_url",
                    models.URLField(blank=True, null=True, verbose_name="file URL"),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="file size"
                    ),
                ),
                (
                    "filter_session_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="filter session ID",
                    ),
                ),
                (
                    "filter_department",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="filter department",
                    ),
                ),
                (
                    "filter_property",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="filter property",
                    ),
                ),
                (
                    "filter_asset_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="filter asset type",
                    ),
                ),
                (
                    "created_by_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="created by name",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="error message"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "report",
                "verbose_name_plural": "reports",
                "db_table": "reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["type"], name="reports_type_4f55c9_idx"),
                    models.Index(fields=["status"], name="reports_status_e83c1d_idx"),
                    models.Index(
                        fields=["date_from"], name="reports_date_fr_647089_idx"
                    ),
                    models.Index(fields=["date_to"], name="reports_date_to_96ac16_idx"),
                ],
            },
        ),
    ]
