# Generated by Django 5.1.4 on 2026-07-02 08:02

import django.db.models.deletion
import employees.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="employee ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="full name"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="national ID",
                    ),
                ),
                (
                    "job_position",
                    models.CharField(max_length=255, verbose_name="job position"),
                ),
                (
                    "job_grade",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="job grade"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="hire date"),
                ),
                (
                    "family_size",
                    models.PositiveIntegerField(default=0, verbose_name="family size"),
                ),
                (
                    "has_disability",
                    models.BooleanField(default=False, verbose_name="has disability"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("On Leave", "On Leave"),
                            ("Terminated", "Terminated"),
                        ],
                        db_index=True,
                        default="Active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "cv_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=employees.models.employee_cv_upload_path,
                        verbose_name="CV file",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="departments.department",
                        verbose_name="department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "employee",
                "verbose_name_plural": "employees",
                "db_table": "employees",
                "ordering": ["employee_id"],
                "indexes": [
                    models.Index(
                        fields=["employee_id"], name="employees_employe_0b5eb0_idx"
                    ),
                    models.Index(
                        fields=["national_id"], name="employees_nationa_268f02_idx"
                    ),
                    models.Index(fields=["status"], name="employees_status_0192ac_idx"),
                    models.Index(
                        fields=["department"], name="employees_departm_24ab5f_idx"
                    ),
                ],
            },
        ),
    ]
