# Generated by Django 5.1.4 on 2026-08-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_add_marital_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Permanent", "Permanent"),
                    ("Semi Permanent", "Semi Permanent"),
                    ("Seasonal", "Seasonal"),
                ],
                default="Permanent",
                max_length=20,
                verbose_name="job type",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="names",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Additional names or preferred name (nickname, middle name, etc.)",
                max_length=255,
                verbose_name="names",
            ),
        ),
    ]
