# Generated by Django 5.1.4 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_job_type_employee_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(
                db_index=True,
                help_text="Manually assigned employee code (e.g. EMP-00001). Entered by HR, never auto-generated.",
                max_length=20,
                unique=True,
                verbose_name="employee ID",
            ),
        ),
    ]
