# Generated by Django 5.1.4 on 2026-08-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_employee_id_manual_required"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="names",
        ),
    ]
