# Generated by Django 5.1.4 on 2026-07-01 08:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "department",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="department"
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="assigned at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit assignment",
                "verbose_name_plural": "audit assignments",
                "db_table": "audit_assignments",
            },
        ),
        migrations.CreateModel(
            name="AuditIncharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "role",
                    models.CharField(
                        default="incharge", max_length=50, verbose_name="role"
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="assigned at"),
                ),
            ],
            options={
                "verbose_name": "audit incharge",
                "verbose_name_plural": "audit incharges",
                "db_table": "audit_incharge",
            },
        ),
        migrations.CreateModel(
            name="AuditReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "report_type",
                    models.CharField(
                        default="summary", max_length=50, verbose_name="report type"
                    ),
                ),
                (
                    "file_url",
                    models.URLField(blank=True, null=True, verbose_name="file URL"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="generated at"
                    ),
                ),
                (
                    "summary",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="summary"
                    ),
                ),
            ],
            options={
                "verbose_name": "audit report",
                "verbose_name_plural": "audit reports",
                "db_table": "audit_reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "assets_reviewed",
                    models.IntegerField(default=0, verbose_name="assets reviewed"),
                ),
                (
                    "verified_count",
                    models.IntegerField(default=0, verbose_name="verified count"),
                ),
                (
                    "damaged_count",
                    models.IntegerField(default=0, verbose_name="damaged count"),
                ),
                (
                    "missing_count",
                    models.IntegerField(default=0, verbose_name="missing count"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="submitted at"
                    ),
                ),
            ],
            options={
                "verbose_name": "audit review",
                "verbose_name_plural": "audit reviews",
                "db_table": "audit_reviews",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "asset_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="asset ID"
                    ),
                ),
                (
                    "property_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="property ID"
                    ),
                ),
                (
                    "department",
                    models.CharField(max_length=255, verbose_name="department"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("damaged", "Damaged"),
                            ("missing", "Missing"),
                        ],
                        default="verified",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "scanned_by_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="scanned by name",
                    ),
                ),
                (
                    "scanned_by_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="scanned by email",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="comment"),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="scanned at"
                    ),
                ),
            ],
            options={
                "verbose_name": "audit scan",
                "verbose_name_plural": "audit scans",
                "db_table": "audit_scans",
                "ordering": ["-scanned_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="session ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("ad_hoc", "Ad Hoc"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(db_index=True, verbose_name="scheduled date"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="end date"
                    ),
                ),
                (
                    "total_assets",
                    models.IntegerField(default=0, verbose_name="total assets"),
                ),
                (
                    "verified_assets",
                    models.IntegerField(default=0, verbose_name="verified assets"),
                ),
                (
                    "damaged_assets",
                    models.IntegerField(default=0, verbose_name="damaged assets"),
                ),
                (
                    "missing_assets",
                    models.IntegerField(default=0, verbose_name="missing assets"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
            ],
            options={
                "verbose_name": "audit session",
                "verbose_name_plural": "audit sessions",
                "db_table": "audit_sessions",
                "ordering": ["-scheduled_date"],
            },
        ),
    ]
