"""
Metahara Sugar Factory — Official Fixed Asset Registration Master Book.

Complete enterprise asset classification with codes for every asset item.
Groups (Category) and sub-items (ItemType) form a two-level hierarchy.

Structure:
  Group code (e.g. "01") → Category record
  Item code  (e.g. "1.1") → ItemType record linked to parent Category
"""
from __future__ import annotations

# ── Master asset classification ──────────────────────────────────────────────
# Each group: (group_code, group_name, [(item_code, item_name), ...])

ASSET_MASTER: list[tuple[str, str, list[tuple[str, str]]]] = [
    ("01", "Irrigation System", [
        ("1.1", "Irrigation Pumps"),
        ("1.2", "Reservoirs"),
        ("1.3", "Canals"),
        ("1.4", "Water Gates"),
    ]),
    ("02", "Bridges and Roads", [
        ("2.1", "Bridges"),
        ("2.2", "Roads"),
    ]),
    ("03", "Factory and Plant Machineries", [
        ("3.39", "Trade Machine"),
        ("3.40", "Planner"),
        ("3.41", "Radar Vertical Drilling Machine"),
        ("3.42", "Bending Machine"),
        ("3.43", "Milling Cutter Grinding Machine"),
        ("3.44", "Drill Bit Grinding Machine"),
        ("3.45", "Power Hack Saw"),
        ("3.46", "Pneumatic Hammer"),
        ("3.47", "Rolling Machine"),
        ("3.48", "Stone Grinding Machine"),
        ("3.49", "Poly Extractor"),
        ("3.50", "Tri Square (Tri For)"),
        ("3.51", "Tri Square"),
        ("3.52", "Hydraulic Bending Machine"),
        ("3.53", "Test Panel"),
        ("3.54", "Dead Weight"),
        ("3.55", "Temperature Tester"),
        ("3.56", "Pneumatic Test Panel"),
        ("3.57", "Resistance Box"),
        ("3.58", "Charging Cylinder"),
        ("3.59", "Soldering Iron (Lead)"),
        ("3.60", "Oven (Heater)"),
        ("3.61", "Electrical Testing Panel"),
        ("3.62", "Winding Machine"),
        ("3.63", "Relay Testing (Instrument)"),
        ("3.64", "Oscilloscope"),
        ("3.65", "High Tension Megger"),
        ("3.66", "Oscillator"),
        ("3.67", "Universal Power Recording"),
        ("3.68", "Vacuum Cleaner"),
        ("3.69", "Rheostat"),
        ("3.70", "Avo-Meter"),
        ("3.71", "Power Factor Measuring"),
        ("3.72", "High Tension Cable Location"),
        ("3.73", "Cable Test Equipments"),
        ("3.74", "Jig Saw"),
        ("3.75", "Watt Hour Meter Tester"),
        ("3.76", "Test Master Kit"),
        ("3.77", "Multi Meter Anigar"),
        ("3.78", "Electric Liner Relay Tester"),
        ("3.79", "Phase Sequence Indicator"),
        ("3.80", "Speedometer"),
        ("3.81", "Phase Continuity Indicator"),
        ("3.82", "Kilovolt/Kiloun Bridge"),
        ("3.83", "Diode Zener"),
        ("3.84", "Crowler"),
        ("3.85", "Paint Spray Equipment"),
        ("3.86", "Letter Embossing Machine"),
        ("3.87", "Earth Resistance Measuring"),
        ("3.88", "Rotary Drawing"),
        ("3.89", "Transformer Auto"),
        ("3.90", "SKF Oil Injection Equipment"),
        ("3.91", "Stroboscope"),
        ("3.92", "Digital Optical Tachometer"),
        ("3.93", "Temperature Measuring Unit"),
        ("3.94", "Power Sources"),
        ("3.95", "Automatic Halogen Leak Detector"),
        ("3.96", "Debro Tester"),
        ("3.97", "Flow Calibrator"),
        ("3.98", "Durometer"),
        ("3.99", "Water and Mercury Gauge"),
        ("3.100", "Drier"),
        ("3.101", "pH Meter"),
        ("3.102", "Saccharimeter"),
        ("3.103", "Moisture Indicator"),
        ("3.104", "Variac / Varagreater"),
        ("3.105", "Refractometer and Hand Refractometer"),
        ("3.106", "Water Cooler / Karl Electronic"),
        ("3.107", "Centrifuge / Cebery Machine"),
        ("3.108", "Conductivity Meter"),
        ("3.109", "Magnetic Stirrer"),
        ("3.110", "Tamson"),
        ("3.111", "Orsat Apparatus"),
        ("3.112", "Milling Lathe Machine"),
        ("3.113", "Conveyor"),
        ("3.114", "Portable Lathe Machine"),
        ("3.115", "Winch"),
        ("3.116", "Concrete Mixer"),
        ("3.117", "Grease Gun"),
        ("3.118", "Generator"),
        ("3.119", "Sewing Machine"),
        ("3.120", "Electric Transformer"),
        ("3.121", "Dynamo"),
        ("3.122", "Sokia Automatic Leveler"),
        ("3.123", "Vibrator Machine"),
        ("3.124", "Electric Press Hydraulic Machine"),
        ("3.125", "Tyre Changer"),
        ("3.126", "Armchair Tester"),
        ("3.127", "Beta Body Repair Kit"),
        ("3.128", "Distiller"),
        ("3.129", "Vagas Drier"),
        ("3.130", "Cane Sample Tumbler Machine"),
        ("3.131", "Wire Cutter"),
        ("3.132", "Thickness Gauge"),
        ("3.133", "Service Engineering Tools Kit"),
        ("3.134", "Efficiency Monitor"),
        ("3.135", "Electrical Panel"),
        ("3.136", "Oxygen Cylindrical Machine"),
        ("3.137", "Horizontal Boring Machine"),
        ("3.138", "Heater Machine"),
        ("3.139", "Rewinding Machine"),
        ("3.140", "Puller"),
        ("3.141", "Radio Communication System"),
        ("3.142", "Spectra Precision Leveling Instrument"),
        ("3.143", "Pneumatic Wrench"),
        ("3.144", "Induction Bearing Heater"),
        ("3.145", "Compression Tester"),
        ("3.146", "Petrol Tester"),
        ("3.147", "Stroboscopic Timing Tester"),
        ("3.148", "Infrared Laser Thermometer"),
        ("3.149", "Hydraulic Power Harrow"),
        ("3.150", "Plasma Cutting Machine"),
    ]),
    ("04", "Heavy Equipment", [
        ("4.1", "Dump Trucks"),
        ("4.2", "Buses"),
        ("4.3", "Fire Fighting Trucks"),
        ("4.4", "Trucks"),
        ("4.5", "Trailers Goods"),
    ]),
    ("05", "Light Vehicles", [
        ("5.1", "Pick Ups"),
        ("5.2", "Motor Cycles"),
        ("5.3", "Bicycles"),
        ("5.4", "Estate Cars"),
    ]),
    ("06", "Office Furniture and Equipment", [
        ("6.1", "Chair"),
        ("6.2", "Desk"),
        ("6.3", "Conference Table"),
        ("6.4", "Ordinary Table"),
        ("6.5", "Shelf (Wooden)"),
        ("6.6", "Shelf (Metal)"),
        ("6.7", "Filing Cabinet (Wooden)"),
        ("6.8", "Filing Cabinet (Metal)"),
        ("6.9", "Cupboard (Wooden)"),
        ("6.10", "Cupboard (Metal)"),
        ("6.11", "Box (Wooden)"),
        ("6.12", "Box (Metal)"),
        ("6.13", "Calculating Machines"),
        ("6.14", "Typewriter Amharic"),
        ("6.15", "Typewriter English"),
        ("6.16", "Duplicating Machine"),
        ("6.17", "Photocopy Machine"),
        ("6.18", "Intercom"),
        ("6.19", "Ventilator"),
        ("6.20", "Shutter"),
        ("6.21", "Stool"),
        ("6.22", "Bench"),
        ("6.23", "Paper Cutter"),
        ("6.24", "Air Conditioner"),
        ("6.25", "Safe"),
        ("6.26", "Drawing Clamps"),
        ("6.27", "Convertible Table"),
        ("6.28", "Perforator"),
        ("6.29", "Drawing Table"),
        ("6.30", "Time Card Puncher"),
        ("6.31", "Lock Sheet (Wooden)"),
        ("6.32", "Work Bench"),
        ("6.33", "Card Box / Roller"),
        ("6.34", "Bins"),
        ("6.35", "Lock Sheet (Metal)"),
        ("6.36", "Dental Chair"),
        ("6.37", "Sink"),
        ("6.39", "Drawer Shelf"),
        ("6.40", "Computer"),
        ("6.41", "Laptop Computer"),
        ("6.42", "Laminator (Lamipacker)"),
        ("6.43", "Atlas AS Punch"),
        ("6.44", "Drafting Room Hanger"),
        ("6.45", "CD Writer Multi Read/Recorder"),
        ("6.46", "Ring Binder"),
        ("6.47", "Electrical Bell with 12 Station"),
        ("6.48", "Stapler Machine"),
        ("6.49", "Scanner"),
        ("6.50", "Cash Register"),
        ("6.51", "Server"),
        ("6.52", "Plastic Film Sealer"),
    ]),
    ("07", "Household Furniture & Equipment", [
        ("7.1", "Beds"),
        ("7.2", "Mattress"),
        ("7.3", "Chairs"),
        ("7.4", "Radio"),
        ("7.5", "Television"),
        ("7.6", "Stove"),
        ("7.7", "Refrigerator"),
        ("7.8", "Table"),
        ("7.9", "Water Heater"),
        ("7.10", "Water Cooler"),
        ("7.11", "Stool / Bar Chair"),
        ("7.12", "Cupboard (Wooden)"),
        ("7.13", "Cupboard (Metal)"),
        ("7.14", "Bed Side Ladder"),
        ("7.16", "Screen"),
        ("7.17", "Shelf (Metal)"),
        ("7.18", "Shelf (Wooden)"),
        ("7.19", "Box (Wooden)"),
        ("7.20", "Box (Metal)"),
        ("7.21", "Coffee Grinder"),
        ("7.22", "Slice Cutter"),
        ("7.23", "Meat Grinder"),
        ("7.24", "Heat & Fire Extinguisher / Fan"),
        ("7.25", "Bench"),
        ("7.26", "Air Conditioner"),
        ("7.27", "Stool Table"),
        ("7.28", "Buffet"),
        ("7.29", "Iron"),
        ("7.30", "Reading Lamp"),
        ("7.31", "Ventilator"),
        ("7.32", "Desk"),
        ("7.33", "Bed Side Commodino"),
        ("7.34", "Dressing Table"),
        ("7.35", "Ironing Table"),
        ("7.36", "Ice Box"),
        ("7.37", "Stretcher"),
        ("7.38", "Injera Baker (Meto)"),
        ("7.39", "Shredder"),
        ("7.40", "Kitchen Sink with Shelf"),
        ("7.41", "Kitchen Commodino"),
        ("7.42", "Sink"),
        ("7.43", "Mirror"),
        ("7.44", "Over Head Shower"),
        ("7.45", "Telephone Shower"),
        ("7.46", "Kitchen Shelf"),
        ("7.47", "Store Shelf"),
        ("7.48", "Towel Hanger"),
        ("7.49", "Tissue Paper Holder"),
        ("7.50", "Water Pail"),
        ("7.51", "Tape Recorder"),
        ("7.52", "Table Chair"),
        ("7.53", "Laundry Machine"),
        ("7.54", "Saucepan"),
        ("7.56", "TV Seat"),
        ("7.57", "Canon Fax Biso"),
        ("7.58", "TV Antenna"),
    ]),
    ("08", "Agricultural Machines & Equipment", [
        ("8.1", "Tractors"),
        ("8.2", "Dozers"),
        ("8.3", "D4 + Grap"),
        ("8.4", "Scrapers"),
        ("8.5", "Sprayers"),
        ("8.6", "Trailers"),
        ("8.7", "Graders"),
        ("8.8", "Low Bed"),
        ("8.9", "Light Unit"),
        ("8.10", "Loader Gravel"),
        ("8.11", "Plainer"),
        ("8.12", "Dredger / Booster"),
        ("8.13", "NCK Pocklain"),
        ("8.14", "Harrower"),
        ("8.15", "Plough"),
        ("8.16", "Moulder"),
        ("8.17", "Fertilizer Hopper"),
        ("8.18", "Flatner"),
        ("8.19", "Chemical Sprayer"),
        ("8.20", "Sub Soiler"),
        ("8.21", "Bush Reck"),
        ("8.22", "Furrower"),
        ("8.23", "Dozer Blade"),
        ("8.24", "P & H Crane"),
        ("8.25", "Trash Reck"),
        ("8.26", "Solution Tank FES"),
        ("8.27", "Water Bottle"),
        ("8.28", "Slasher Grass"),
        ("8.29", "Roller"),
        ("8.30", "Trash Trailer"),
        ("8.31", "W.C Tank"),
        ("8.32", "Monitor"),
        ("8.33", "Scum Spreader"),
    ]),
    ("09", "Buildings", [
        ("9.1", "Offices"),
        ("9.2", "Factory"),
        ("9.3", "Ware Houses & Other Stores"),
        ("9.4", "Clubs / Guest Houses"),
        ("9.5", "Staff Houses"),
        ("9.6", "A-Houses"),
        ("9.7", "B-Houses"),
        ("9.8", "C-Houses"),
        ("9.9", "D-Houses"),
        ("9.10", "H-Houses - Concrete Barak / Rooms"),
        ("9.11", "Chicka Barack - 12 Rooms"),
        ("9.12", "Chicka Barack - 6 Rooms"),
        ("9.13", "E-Houses - Concrete Barak 12 Rooms"),
        ("9.14", "GF-Houses Chicka"),
        ("9.15", "Water Wells"),
        ("9.16", "Staff Service Houses"),
        ("9.17", "Water Tanker"),
        ("9.18", "A-House Service Houses"),
        ("9.19", "Elect. Transformer Houses"),
        ("9.20", "Stone Houses Orchard Village"),
        ("9.21", "Ground Tennis Court"),
        ("9.22", "Swimming Pool"),
        ("9.23", "Guard House"),
        ("9.24", "Shade"),
        ("9.25", "Wood Workshop"),
        ("9.26", "Tawal House"),
        ("9.27", "Kitchen"),
        ("9.28", "Garage"),
        ("9.29", "Fuel Depot"),
        ("9.30", "Staff D - Abadir"),
        ("9.31", "Staff C - Abadir"),
        ("9.32", "Staff B - Abadir"),
        ("9.33", "Bakery"),
        ("9.34", "Toilet"),
        ("9.35", "Swimming W.C & Shower"),
        ("9.36", "Basketball Court"),
        ("9.37", "Wedding Stage"),
        ("9.38", "Corcuro"),
        ("9.39", "Container 12m / 6m"),
        ("9.40", "Battery Stage / Jumper"),
    ]),
    ("10", "Miscellaneous Assets", [
        ("10.1", "Com Chairman Picture"),
        ("10.2", "Projector / Slide Film"),
        ("10.3", "Transformer / Film Power Control Amplifier"),
        ("10.4", "Amplifier"),
        ("10.5", "Speaker"),
        ("10.6", "Restroom"),
        ("10.7", "Film Rewinder"),
        ("10.8", "Ticket Sell Box"),
        ("10.9", "Map"),
        ("10.10", "Globe"),
        ("10.11", "Wall Pictures"),
        ("10.12", "Planning Board"),
        ("10.13", "Insect Collector"),
        ("10.14", "Balance / Scale"),
        ("10.15", "Wind Vane"),
        ("10.16", "Rain Gauge"),
        ("10.17", "Picture Stand"),
        ("10.18", "Hanger"),
        ("10.19", "Award Display - Metal Shelf"),
        ("10.20", "Brief-Case"),
        ("10.21", "Black Board"),
        ("10.22", "Communication Radio"),
        ("10.23", "Trolley"),
        ("10.24", "Wall Clock"),
        ("10.25", "Suction"),
        ("10.26", "Drum"),
        ("10.27", "Prism"),
        ("10.28", "Sprayer"),
        ("10.29", "Soil Boring"),
        ("10.30", "Lab. Inst. Stand"),
        ("10.31", "Electrical Water Pump"),
        ("10.32", "Photo Camera"),
        ("10.33", "Pontoons / Bouyous Bridge"),
        ("10.34", "Billiard Table"),
        ("10.35", "Billiard Score Recording"),
        ("10.36", "Billiard Stick Holder"),
        ("10.37", "Piano"),
        ("10.38", "Lens"),
        ("10.40", "Film Splicing Device"),
        ("10.41", "Stabilizer"),
        ("10.42", "Microfilm Reader"),
        ("10.43", "Cobas C-311 Analyzer / Turbine Moden"),
        ("10.44", "Books"),
        ("10.45", "Micrometer"),
        ("10.46", "Compass"),
        ("10.47", "Printing Machine"),
        ("10.48", "Rapido Graph"),
        ("10.49", "Spirit Level"),
        ("10.50", "Trammel Compass"),
        ("10.51", "Measuring Protractor"),
        ("10.52", "Ladder"),
        ("10.53", "Sugar Cart"),
        ("10.54", "Oxygen Cylinder"),
        ("10.55", "Wheel Barrow"),
        ("10.56", "Megaphone"),
        ("10.57", "Human Anatomical Picture"),
        ("10.58", "X-Ray Viewer Lamp / Odelca Magnifier Mirror"),
        ("10.60", "X-Ray Apparatus"),
        ("10.61", "Centrifuge"),
        ("10.62", "Microscope"),
        ("10.63", "Vitaron"),
        ("10.64", "X-Ray Film Drier Machine"),
        ("10.65", "Odelca Film Holder"),
        ("10.66", "X-Ray Chest Stand"),
        ("10.67", "X-Ray Printer"),
        ("10.68", "X-Ray Film Holder Box"),
        ("10.69", "X-Ray Timing Device / Odelca Tube"),
        ("10.70", "Odelca Film Developing Device"),
        ("10.71", "Needle Sterilizer"),
        ("10.72", "Steam Sterilizer"),
        ("10.73", "Operation Lamp"),
        ("10.74", "Weight Standard Stone"),
        ("10.75", "Fork Lift"),
        ("10.76", "Tripod"),
        ("10.77", "Stadia Meter / Distance Measuring"),
        ("10.79", "Tri-Square"),
        ("10.80", "Ground Tennis Net"),
        ("10.81", "Ground Tennis Court Roller"),
        ("10.82", "Ground Tennis Referee Seat"),
        ("10.83", "Video Deck"),
        ("10.84", "Film Reel"),
        ("10.85", "Fire Extinguisher"),
        ("10.86", "Differential Counter"),
        ("10.87", "Juice Squeezer"),
        ("10.88", "Hand Stretcher / Chair"),
        ("10.89", "Coach Bed"),
        ("10.90", "Odelca Machine & Apparatus"),
        ("10.91", "Odelca Film Drier"),
        ("10.92", "Hyundai X-Ray Machine"),
        ("10.93", "Corner Lamp"),
        ("10.94", "Overhead Projector & Screen with Stand"),
        ("10.95", "Photo Camera Stand"),
        ("10.97", "Gifco Grinder"),
        ("10.98", "Sugar Sales Box"),
        ("10.99", "Mobile Telephone"),
        ("10.100", "Detector"),
        ("10.101", "Satellite Dish"),
        ("10.102", "Notice Board"),
        ("10.103", "White Board with Stand"),
        ("10.104", "Water Bath"),
        ("10.105", "Photometer"),
        ("10.106", "Electric Charger Car / Sugar Transport"),
        ("10.107", "Bingo Machine Set"),
        ("10.108", "Multi Choice DSTV"),
        ("10.109", "Programming Controller (Ikusi) for Decoder"),
        ("10.110", "Microphone"),
        ("10.111", "Equibetor"),
        ("10.112", "Lamp Rechargeable"),
        ("10.113", "Atmolit-N"),
        ("10.114", "E.K.G. Electrocardiograph Machine"),
        ("10.115", "Ultrasound 128 BW Machine"),
        ("10.116", "Rewinder - RW 200 / VHS"),
        ("10.117", "Reader 2305"),
        ("10.118", "Washer 430 / Power"),
        ("10.119", "Epson LX-300+ Printer"),
        ("10.120", "Tekan Bottle Holder"),
        ("10.121", "Labour Photometer LP420"),
        ("10.122", "Vacuum"),
        ("10.123", "Dental Machine Swivel"),
        ("10.124", "Dental X-Ray Machine / Hematology Analyzer"),
        ("10.125", "Dental Instrument Container Swivel"),
        ("10.126", "UPS for Furnace / Voltage Regulator"),
        ("10.127", "Counting System / Movable Screen"),
        ("10.128", "Facs Court System / TV Transmission Machine"),
        ("10.129", "Chemistry Analyzer / Medical Device Machine"),
        ("10.131", "Umbrella"),
        ("10.132", "Sysmex / Genex / Cobas C-311 Dazter"),
        ("10.133", "Printer Thermal"),
        ("10.135", "Plastic Pallets"),
        ("10.136", "Electric Telephone Pole"),
        ("10.137", "Roost"),
        ("10.138", "Wireless Microscope"),
        ("10.139", "Hair Dryer Unit"),
    ]),
]


# ── Helper lookups ──────────────────────────────────────────────────────────

# group_code -> group_name
GROUP_BY_CODE: dict[str, str] = {
    code: name for code, name, _items in ASSET_MASTER
}

# item_code -> (item_name, group_code)
ITEM_BY_CODE: dict[str, tuple[str, str]] = {
    item_code: (item_name, group_code)
    for group_code, group_name, items in ASSET_MASTER
    for item_code, item_name in items
}

# group_code -> [(item_code, item_name)]
ITEMS_BY_GROUP: dict[str, list[tuple[str, str]]] = {
    group_code: items for group_code, _name, items in ASSET_MASTER
}

# Flat list of (item_code, item_name, group_code, group_name) for serializers
ALL_ITEMS: list[tuple[str, str, str, str]] = [
    (item_code, item_name, group_code, group_name)
    for group_code, group_name, items in ASSET_MASTER
    for item_code, item_name in items
]

# Asset code prefix by group
GROUP_PREFIX: dict[str, str] = {
    "01": "1",
    "02": "2",
    "03": "3",
    "04": "4",
    "05": "5",
    "06": "6",
    "07": "7",
    "08": "8",
    "09": "9",
    "10": "10",
}
