# Generated by Django 5.1.4 on 2026-07-08 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_initial"),
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceticket",
            name="close_note",
            field=models.TextField(blank=True, null=True, verbose_name="close note"),
        ),
        migrations.AddField(
            model_name="maintenanceticket",
            name="property_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="property ID",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceticket",
            name="target_role",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="target role"
            ),
        ),
        migrations.AlterField(
            model_name="maintenanceticket",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_tickets",
                to="assets.asset",
                verbose_name="asset",
            ),
        ),
    ]
