# Generated by Django 5.1.4 on 2026-07-01 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseMeta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "key",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="key"
                    ),
                ),
                ("value", models.JSONField(verbose_name="value")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "license metadata",
                "verbose_name_plural": "license metadata",
                "db_table": "license_meta",
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "id",
                    models.BooleanField(
                        default=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=50, verbose_name="timezone"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", max_length=10, verbose_name="language"
                    ),
                ),
                (
                    "backup_frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="backup frequency",
                    ),
                ),
                (
                    "auto_backup",
                    models.BooleanField(default=True, verbose_name="auto backup"),
                ),
                (
                    "appearance",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="appearance"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "system settings",
                "verbose_name_plural": "system settings",
                "db_table": "system_settings",
            },
        ),
        migrations.CreateModel(
            name="PropertyLicense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "property_id",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="property ID",
                    ),
                ),
                (
                    "asset_limit",
                    models.IntegerField(
                        default=0, help_text="0 = unlimited", verbose_name="asset limit"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("free", "Free"),
                            ("standard", "Standard"),
                            ("pro", "Pro"),
                            ("business", "Business"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="plan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "property license",
                "verbose_name_plural": "property licenses",
                "db_table": "property_license",
                "indexes": [
                    models.Index(
                        fields=["property_id"], name="property_li_propert_fa27e9_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RecentActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("asset_created", "Asset Created"),
                            ("asset_updated", "Asset Updated"),
                            ("asset_deleted", "Asset Deleted"),
                            ("qr_generated", "QR Generated"),
                            ("report", "Report"),
                            ("approval", "Approval"),
                            ("ticket", "Ticket"),
                            ("audit", "Audit"),
                            ("user", "User"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=30,
                        verbose_name="type",
                    ),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="user name"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "recent activity",
                "verbose_name_plural": "recent activities",
                "db_table": "recent_activity",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="recent_acti_user_id_239a66_idx"
                    ),
                    models.Index(fields=["type"], name="recent_acti_type_9a4866_idx"),
                    models.Index(
                        fields=["created_at"], name="recent_acti_created_045533_idx"
                    ),
                ],
            },
        ),
    ]
