# Generated by Django 5.1.4 on 2026-08-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertylicense",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="propertylicense",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="LicenseMeta",
        ),
        migrations.DeleteModel(
            name="PropertyLicense",
        ),
    ]
