# Generated by Django 5.1.4 on 2026-08-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False, verbose_name="must change password"
            ),
        ),
    ]
