/**
 * Metahara Sugar Factory — Fixed Asset Registration Master Book
 *
 * 10 asset groups with 440 sub-items, each with official codes.
 * This is the single source of truth for asset classification on the frontend.
 */

export type AssetGroup = {
  code: string;
  name: string;
  items: AssetItem[];
};

export type AssetItem = {
  code: string;
  name: string;
  groupCode: string;
};

export const ASSET_GROUPS: AssetGroup[] = [
  {
    code: "01", name: "Irrigation System", items: [
      { code: "1.1", name: "Irrigation Pumps", groupCode: "01" },
      { code: "1.2", name: "Reservoirs", groupCode: "01" },
      { code: "1.3", name: "Canals", groupCode: "01" },
      { code: "1.4", name: "Water Gates", groupCode: "01" },
    ],
  },
  {
    code: "02", name: "Bridges and Roads", items: [
      { code: "2.1", name: "Bridges", groupCode: "02" },
      { code: "2.2", name: "Roads", groupCode: "02" },
    ],
  },
  {
    code: "03", name: "Factory and Plant Machineries", items: [
      { code: "3.39", name: "Trade Machine", groupCode: "03" },
      { code: "3.40", name: "Planner", groupCode: "03" },
      { code: "3.41", name: "Radar Vertical Drilling Machine", groupCode: "03" },
      { code: "3.42", name: "Bending Machine", groupCode: "03" },
      { code: "3.43", name: "Milling Cutter Grinding Machine", groupCode: "03" },
      { code: "3.44", name: "Drill Bit Grinding Machine", groupCode: "03" },
      { code: "3.45", name: "Power Hack Saw", groupCode: "03" },
      { code: "3.46", name: "Pneumatic Hammer", groupCode: "03" },
      { code: "3.47", name: "Rolling Machine", groupCode: "03" },
      { code: "3.48", name: "Stone Grinding Machine", groupCode: "03" },
      { code: "3.49", name: "Poly Extractor", groupCode: "03" },
      { code: "3.50", name: "Tri Square (Tri For)", groupCode: "03" },
      { code: "3.51", name: "Tri Square", groupCode: "03" },
      { code: "3.52", name: "Hydraulic Bending Machine", groupCode: "03" },
      { code: "3.53", name: "Test Panel", groupCode: "03" },
      { code: "3.54", name: "Dead Weight", groupCode: "03" },
      { code: "3.55", name: "Temperature Tester", groupCode: "03" },
      { code: "3.56", name: "Pneumatic Test Panel", groupCode: "03" },
      { code: "3.57", name: "Resistance Box", groupCode: "03" },
      { code: "3.58", name: "Charging Cylinder", groupCode: "03" },
      { code: "3.59", name: "Soldering Iron (Lead)", groupCode: "03" },
      { code: "3.60", name: "Oven (Heater)", groupCode: "03" },
      { code: "3.61", name: "Electrical Testing Panel", groupCode: "03" },
      { code: "3.62", name: "Winding Machine", groupCode: "03" },
      { code: "3.63", name: "Relay Testing (Instrument)", groupCode: "03" },
      { code: "3.64", name: "Oscilloscope", groupCode: "03" },
      { code: "3.65", name: "High Tension Megger", groupCode: "03" },
      { code: "3.66", name: "Oscillator", groupCode: "03" },
      { code: "3.67", name: "Universal Power Recording", groupCode: "03" },
      { code: "3.68", name: "Vacuum Cleaner", groupCode: "03" },
      { code: "3.69", name: "Rheostat", groupCode: "03" },
      { code: "3.70", name: "Avo-Meter", groupCode: "03" },
      { code: "3.71", name: "Power Factor Measuring", groupCode: "03" },
      { code: "3.72", name: "High Tension Cable Location", groupCode: "03" },
      { code: "3.73", name: "Cable Test Equipments", groupCode: "03" },
      { code: "3.74", name: "Jig Saw", groupCode: "03" },
      { code: "3.75", name: "Watt Hour Meter Tester", groupCode: "03" },
      { code: "3.76", name: "Test Master Kit", groupCode: "03" },
      { code: "3.77", name: "Multi Meter Anigar", groupCode: "03" },
      { code: "3.78", name: "Electric Liner Relay Tester", groupCode: "03" },
      { code: "3.79", name: "Phase Sequence Indicator", groupCode: "03" },
      { code: "3.80", name: "Speedometer", groupCode: "03" },
      { code: "3.81", name: "Phase Continuity Indicator", groupCode: "03" },
      { code: "3.82", name: "Kilovolt/Kiloun Bridge", groupCode: "03" },
      { code: "3.83", name: "Diode Zener", groupCode: "03" },
      { code: "3.84", name: "Crowler", groupCode: "03" },
      { code: "3.85", name: "Paint Spray Equipment", groupCode: "03" },
      { code: "3.86", name: "Letter Embossing Machine", groupCode: "03" },
      { code: "3.87", name: "Earth Resistance Measuring", groupCode: "03" },
      { code: "3.88", name: "Rotary Drawing", groupCode: "03" },
      { code: "3.89", name: "Transformer Auto", groupCode: "03" },
      { code: "3.90", name: "SKF Oil Injection Equipment", groupCode: "03" },
      { code: "3.91", name: "Stroboscope", groupCode: "03" },
      { code: "3.92", name: "Digital Optical Tachometer", groupCode: "03" },
      { code: "3.93", name: "Temperature Measuring Unit", groupCode: "03" },
      { code: "3.94", name: "Power Sources", groupCode: "03" },
      { code: "3.95", name: "Automatic Halogen Leak Detector", groupCode: "03" },
      { code: "3.96", name: "Debro Tester", groupCode: "03" },
      { code: "3.97", name: "Flow Calibrator", groupCode: "03" },
      { code: "3.98", name: "Durometer", groupCode: "03" },
      { code: "3.99", name: "Water and Mercury Gauge", groupCode: "03" },
      { code: "3.100", name: "Drier", groupCode: "03" },
      { code: "3.101", name: "pH Meter", groupCode: "03" },
      { code: "3.102", name: "Saccharimeter", groupCode: "03" },
      { code: "3.103", name: "Moisture Indicator", groupCode: "03" },
      { code: "3.104", name: "Variac / Varagreater", groupCode: "03" },
      { code: "3.105", name: "Refractometer and Hand Refractometer", groupCode: "03" },
      { code: "3.106", name: "Water Cooler / Karl Electronic", groupCode: "03" },
      { code: "3.107", name: "Centrifuge / Cebery Machine", groupCode: "03" },
      { code: "3.108", name: "Conductivity Meter", groupCode: "03" },
      { code: "3.109", name: "Magnetic Stirrer", groupCode: "03" },
      { code: "3.110", name: "Tamson", groupCode: "03" },
      { code: "3.111", name: "Orsat Apparatus", groupCode: "03" },
      { code: "3.112", name: "Milling Lathe Machine", groupCode: "03" },
      { code: "3.113", name: "Conveyor", groupCode: "03" },
      { code: "3.114", name: "Portable Lathe Machine", groupCode: "03" },
      { code: "3.115", name: "Winch", groupCode: "03" },
      { code: "3.116", name: "Concrete Mixer", groupCode: "03" },
      { code: "3.117", name: "Grease Gun", groupCode: "03" },
      { code: "3.118", name: "Generator", groupCode: "03" },
      { code: "3.119", name: "Sewing Machine", groupCode: "03" },
      { code: "3.120", name: "Electric Transformer", groupCode: "03" },
      { code: "3.121", name: "Dynamo", groupCode: "03" },
      { code: "3.122", name: "Sokia Automatic Leveler", groupCode: "03" },
      { code: "3.123", name: "Vibrator Machine", groupCode: "03" },
      { code: "3.124", name: "Electric Press Hydraulic Machine", groupCode: "03" },
      { code: "3.125", name: "Tyre Changer", groupCode: "03" },
      { code: "3.126", name: "Armchair Tester", groupCode: "03" },
      { code: "3.127", name: "Beta Body Repair Kit", groupCode: "03" },
      { code: "3.128", name: "Distiller", groupCode: "03" },
      { code: "3.129", name: "Vagas Drier", groupCode: "03" },
      { code: "3.130", name: "Cane Sample Tumbler Machine", groupCode: "03" },
      { code: "3.131", name: "Wire Cutter", groupCode: "03" },
      { code: "3.132", name: "Thickness Gauge", groupCode: "03" },
      { code: "3.133", name: "Service Engineering Tools Kit", groupCode: "03" },
      { code: "3.134", name: "Efficiency Monitor", groupCode: "03" },
      { code: "3.135", name: "Electrical Panel", groupCode: "03" },
      { code: "3.136", name: "Oxygen Cylindrical Machine", groupCode: "03" },
      { code: "3.137", name: "Horizontal Boring Machine", groupCode: "03" },
      { code: "3.138", name: "Heater Machine", groupCode: "03" },
      { code: "3.139", name: "Rewinding Machine", groupCode: "03" },
      { code: "3.140", name: "Puller", groupCode: "03" },
      { code: "3.141", name: "Radio Communication System", groupCode: "03" },
      { code: "3.142", name: "Spectra Precision Leveling Instrument", groupCode: "03" },
      { code: "3.143", name: "Pneumatic Wrench", groupCode: "03" },
      { code: "3.144", name: "Induction Bearing Heater", groupCode: "03" },
      { code: "3.145", name: "Compression Tester", groupCode: "03" },
      { code: "3.146", name: "Petrol Tester", groupCode: "03" },
      { code: "3.147", name: "Stroboscopic Timing Tester", groupCode: "03" },
      { code: "3.148", name: "Infrared Laser Thermometer", groupCode: "03" },
      { code: "3.149", name: "Hydraulic Power Harrow", groupCode: "03" },
      { code: "3.150", name: "Plasma Cutting Machine", groupCode: "03" },
    ],
  },
  {
    code: "04", name: "Heavy Equipment", items: [
      { code: "4.1", name: "Dump Trucks", groupCode: "04" },
      { code: "4.2", name: "Buses", groupCode: "04" },
      { code: "4.3", name: "Fire Fighting Trucks", groupCode: "04" },
      { code: "4.4", name: "Trucks", groupCode: "04" },
      { code: "4.5", name: "Trailers Goods", groupCode: "04" },
    ],
  },
  {
    code: "05", name: "Light Vehicles", items: [
      { code: "5.1", name: "Pick Ups", groupCode: "05" },
      { code: "5.2", name: "Motor Cycles", groupCode: "05" },
      { code: "5.3", name: "Bicycles", groupCode: "05" },
      { code: "5.4", name: "Estate Cars", groupCode: "05" },
    ],
  },
  {
    code: "06", name: "Office Furniture and Equipment", items: [
      { code: "6.1", name: "Chair", groupCode: "06" },
      { code: "6.2", name: "Desk", groupCode: "06" },
      { code: "6.3", name: "Conference Table", groupCode: "06" },
      { code: "6.4", name: "Ordinary Table", groupCode: "06" },
      { code: "6.5", name: "Shelf (Wooden)", groupCode: "06" },
      { code: "6.6", name: "Shelf (Metal)", groupCode: "06" },
      { code: "6.7", name: "Filing Cabinet (Wooden)", groupCode: "06" },
      { code: "6.8", name: "Filing Cabinet (Metal)", groupCode: "06" },
      { code: "6.9", name: "Cupboard (Wooden)", groupCode: "06" },
      { code: "6.10", name: "Cupboard (Metal)", groupCode: "06" },
      { code: "6.11", name: "Box (Wooden)", groupCode: "06" },
      { code: "6.12", name: "Box (Metal)", groupCode: "06" },
      { code: "6.13", name: "Calculating Machines", groupCode: "06" },
      { code: "6.14", name: "Typewriter Amharic", groupCode: "06" },
      { code: "6.15", name: "Typewriter English", groupCode: "06" },
      { code: "6.16", name: "Duplicating Machine", groupCode: "06" },
      { code: "6.17", name: "Photocopy Machine", groupCode: "06" },
      { code: "6.18", name: "Intercom", groupCode: "06" },
      { code: "6.19", name: "Ventilator", groupCode: "06" },
      { code: "6.20", name: "Shutter", groupCode: "06" },
      { code: "6.21", name: "Stool", groupCode: "06" },
      { code: "6.22", name: "Bench", groupCode: "06" },
      { code: "6.23", name: "Paper Cutter", groupCode: "06" },
      { code: "6.24", name: "Air Conditioner", groupCode: "06" },
      { code: "6.25", name: "Safe", groupCode: "06" },
      { code: "6.26", name: "Drawing Clamps", groupCode: "06" },
      { code: "6.27", name: "Convertible Table", groupCode: "06" },
      { code: "6.28", name: "Perforator", groupCode: "06" },
      { code: "6.29", name: "Drawing Table", groupCode: "06" },
      { code: "6.30", name: "Time Card Puncher", groupCode: "06" },
      { code: "6.31", name: "Lock Sheet (Wooden)", groupCode: "06" },
      { code: "6.32", name: "Work Bench", groupCode: "06" },
      { code: "6.33", name: "Card Box / Roller", groupCode: "06" },
      { code: "6.34", name: "Bins", groupCode: "06" },
      { code: "6.35", name: "Lock Sheet (Metal)", groupCode: "06" },
      { code: "6.36", name: "Dental Chair", groupCode: "06" },
      { code: "6.37", name: "Sink", groupCode: "06" },
      { code: "6.39", name: "Drawer Shelf", groupCode: "06" },
      { code: "6.40", name: "Computer", groupCode: "06" },
      { code: "6.41", name: "Laptop Computer", groupCode: "06" },
      { code: "6.42", name: "Laminator (Lamipacker)", groupCode: "06" },
      { code: "6.43", name: "Atlas AS Punch", groupCode: "06" },
      { code: "6.44", name: "Drafting Room Hanger", groupCode: "06" },
      { code: "6.45", name: "CD Writer Multi Read/Recorder", groupCode: "06" },
      { code: "6.46", name: "Ring Binder", groupCode: "06" },
      { code: "6.47", name: "Electrical Bell with 12 Station", groupCode: "06" },
      { code: "6.48", name: "Stapler Machine", groupCode: "06" },
      { code: "6.49", name: "Scanner", groupCode: "06" },
      { code: "6.50", name: "Cash Register", groupCode: "06" },
      { code: "6.51", name: "Server", groupCode: "06" },
      { code: "6.52", name: "Plastic Film Sealer", groupCode: "06" },
    ],
  },
  {
    code: "07", name: "Household Furniture & Equipment", items: [
      { code: "7.1", name: "Beds", groupCode: "07" },
      { code: "7.2", name: "Mattress", groupCode: "07" },
      { code: "7.3", name: "Chairs", groupCode: "07" },
      { code: "7.4", name: "Radio", groupCode: "07" },
      { code: "7.5", name: "Television", groupCode: "07" },
      { code: "7.6", name: "Stove", groupCode: "07" },
      { code: "7.7", name: "Refrigerator", groupCode: "07" },
      { code: "7.8", name: "Table", groupCode: "07" },
      { code: "7.9", name: "Water Heater", groupCode: "07" },
      { code: "7.10", name: "Water Cooler", groupCode: "07" },
      { code: "7.11", name: "Stool / Bar Chair", groupCode: "07" },
      { code: "7.12", name: "Cupboard (Wooden)", groupCode: "07" },
      { code: "7.13", name: "Cupboard (Metal)", groupCode: "07" },
      { code: "7.14", name: "Bed Side Ladder", groupCode: "07" },
      { code: "7.16", name: "Screen", groupCode: "07" },
      { code: "7.17", name: "Shelf (Metal)", groupCode: "07" },
      { code: "7.18", name: "Shelf (Wooden)", groupCode: "07" },
      { code: "7.19", name: "Box (Wooden)", groupCode: "07" },
      { code: "7.20", name: "Box (Metal)", groupCode: "07" },
      { code: "7.21", name: "Coffee Grinder", groupCode: "07" },
      { code: "7.22", name: "Slice Cutter", groupCode: "07" },
      { code: "7.23", name: "Meat Grinder", groupCode: "07" },
      { code: "7.24", name: "Heat & Fire Extinguisher / Fan", groupCode: "07" },
      { code: "7.25", name: "Bench", groupCode: "07" },
      { code: "7.26", name: "Air Conditioner", groupCode: "07" },
      { code: "7.27", name: "Stool Table", groupCode: "07" },
      { code: "7.28", name: "Buffet", groupCode: "07" },
      { code: "7.29", name: "Iron", groupCode: "07" },
      { code: "7.30", name: "Reading Lamp", groupCode: "07" },
      { code: "7.31", name: "Ventilator", groupCode: "07" },
      { code: "7.32", name: "Desk", groupCode: "07" },
      { code: "7.33", name: "Bed Side Commodino", groupCode: "07" },
      { code: "7.34", name: "Dressing Table", groupCode: "07" },
      { code: "7.35", name: "Ironing Table", groupCode: "07" },
      { code: "7.36", name: "Ice Box", groupCode: "07" },
      { code: "7.37", name: "Stretcher", groupCode: "07" },
      { code: "7.38", name: "Injera Baker (Meto)", groupCode: "07" },
      { code: "7.39", name: "Shredder", groupCode: "07" },
      { code: "7.40", name: "Kitchen Sink with Shelf", groupCode: "07" },
      { code: "7.41", name: "Kitchen Commodino", groupCode: "07" },
      { code: "7.42", name: "Sink", groupCode: "07" },
      { code: "7.43", name: "Mirror", groupCode: "07" },
      { code: "7.44", name: "Over Head Shower", groupCode: "07" },
      { code: "7.45", name: "Telephone Shower", groupCode: "07" },
      { code: "7.46", name: "Kitchen Shelf", groupCode: "07" },
      { code: "7.47", name: "Store Shelf", groupCode: "07" },
      { code: "7.48", name: "Towel Hanger", groupCode: "07" },
      { code: "7.49", name: "Tissue Paper Holder", groupCode: "07" },
      { code: "7.50", name: "Water Pail", groupCode: "07" },
      { code: "7.51", name: "Tape Recorder", groupCode: "07" },
      { code: "7.52", name: "Table Chair", groupCode: "07" },
      { code: "7.53", name: "Laundry Machine", groupCode: "07" },
      { code: "7.54", name: "Saucepan", groupCode: "07" },
      { code: "7.56", name: "TV Seat", groupCode: "07" },
      { code: "7.57", name: "Canon Fax Biso", groupCode: "07" },
      { code: "7.58", name: "TV Antenna", groupCode: "07" },
    ],
  },
  {
    code: "08", name: "Agricultural Machines & Equipment", items: [
      { code: "8.1", name: "Tractors", groupCode: "08" },
      { code: "8.2", name: "Dozers", groupCode: "08" },
      { code: "8.3", name: "D4 + Grap", groupCode: "08" },
      { code: "8.4", name: "Scrapers", groupCode: "08" },
      { code: "8.5", name: "Sprayers", groupCode: "08" },
      { code: "8.6", name: "Trailers", groupCode: "08" },
      { code: "8.7", name: "Graders", groupCode: "08" },
      { code: "8.8", name: "Low Bed", groupCode: "08" },
      { code: "8.9", name: "Light Unit", groupCode: "08" },
      { code: "8.10", name: "Loader Gravel", groupCode: "08" },
      { code: "8.11", name: "Plainer", groupCode: "08" },
      { code: "8.12", name: "Dredger / Booster", groupCode: "08" },
      { code: "8.13", name: "NCK Pocklain", groupCode: "08" },
      { code: "8.14", name: "Harrower", groupCode: "08" },
      { code: "8.15", name: "Plough", groupCode: "08" },
      { code: "8.16", name: "Moulder", groupCode: "08" },
      { code: "8.17", name: "Fertilizer Hopper", groupCode: "08" },
      { code: "8.18", name: "Flatner", groupCode: "08" },
      { code: "8.19", name: "Chemical Sprayer", groupCode: "08" },
      { code: "8.20", name: "Sub Soiler", groupCode: "08" },
      { code: "8.21", name: "Bush Reck", groupCode: "08" },
      { code: "8.22", name: "Furrower", groupCode: "08" },
      { code: "8.23", name: "Dozer Blade", groupCode: "08" },
      { code: "8.24", name: "P & H Crane", groupCode: "08" },
      { code: "8.25", name: "Trash Reck", groupCode: "08" },
      { code: "8.26", name: "Solution Tank FES", groupCode: "08" },
      { code: "8.27", name: "Water Bottle", groupCode: "08" },
      { code: "8.28", name: "Slasher Grass", groupCode: "08" },
      { code: "8.29", name: "Roller", groupCode: "08" },
      { code: "8.30", name: "Trash Trailer", groupCode: "08" },
      { code: "8.31", name: "W.C Tank", groupCode: "08" },
      { code: "8.32", name: "Monitor", groupCode: "08" },
      { code: "8.33", name: "Scum Spreader", groupCode: "08" },
    ],
  },
  {
    code: "09", name: "Buildings", items: [
      { code: "9.1", name: "Offices", groupCode: "09" },
      { code: "9.2", name: "Factory", groupCode: "09" },
      { code: "9.3", name: "Ware Houses & Other Stores", groupCode: "09" },
      { code: "9.4", name: "Clubs / Guest Houses", groupCode: "09" },
      { code: "9.5", name: "Staff Houses", groupCode: "09" },
      { code: "9.6", name: "A-Houses", groupCode: "09" },
      { code: "9.7", name: "B-Houses", groupCode: "09" },
      { code: "9.8", name: "C-Houses", groupCode: "09" },
      { code: "9.9", name: "D-Houses", groupCode: "09" },
      { code: "9.10", name: "H-Houses - Concrete Barak / Rooms", groupCode: "09" },
      { code: "9.11", name: "Chicka Barack - 12 Rooms", groupCode: "09" },
      { code: "9.12", name: "Chicka Barack - 6 Rooms", groupCode: "09" },
      { code: "9.13", name: "E-Houses - Concrete Barak 12 Rooms", groupCode: "09" },
      { code: "9.14", name: "GF-Houses Chicka", groupCode: "09" },
      { code: "9.15", name: "Water Wells", groupCode: "09" },
      { code: "9.16", name: "Staff Service Houses", groupCode: "09" },
      { code: "9.17", name: "Water Tanker", groupCode: "09" },
      { code: "9.18", name: "A-House Service Houses", groupCode: "09" },
      { code: "9.19", name: "Elect. Transformer Houses", groupCode: "09" },
      { code: "9.20", name: "Stone Houses Orchard Village", groupCode: "09" },
      { code: "9.21", name: "Ground Tennis Court", groupCode: "09" },
      { code: "9.22", name: "Swimming Pool", groupCode: "09" },
      { code: "9.23", name: "Guard House", groupCode: "09" },
      { code: "9.24", name: "Shade", groupCode: "09" },
      { code: "9.25", name: "Wood Workshop", groupCode: "09" },
      { code: "9.26", name: "Tawal House", groupCode: "09" },
      { code: "9.27", name: "Kitchen", groupCode: "09" },
      { code: "9.28", name: "Garage", groupCode: "09" },
      { code: "9.29", name: "Fuel Depot", groupCode: "09" },
      { code: "9.30", name: "Staff D - Abadir", groupCode: "09" },
      { code: "9.31", name: "Staff C - Abadir", groupCode: "09" },
      { code: "9.32", name: "Staff B - Abadir", groupCode: "09" },
      { code: "9.33", name: "Bakery", groupCode: "09" },
      { code: "9.34", name: "Toilet", groupCode: "09" },
      { code: "9.35", name: "Swimming W.C & Shower", groupCode: "09" },
      { code: "9.36", name: "Basketball Court", groupCode: "09" },
      { code: "9.37", name: "Wedding Stage", groupCode: "09" },
      { code: "9.38", name: "Corcuro", groupCode: "09" },
      { code: "9.39", name: "Container 12m / 6m", groupCode: "09" },
      { code: "9.40", name: "Battery Stage / Jumper", groupCode: "09" },
    ],
  },
  {
    code: "10", name: "Miscellaneous Assets", items: [
      { code: "10.1", name: "Com Chairman Picture", groupCode: "10" },
      { code: "10.2", name: "Projector / Slide Film", groupCode: "10" },
      { code: "10.3", name: "Transformer / Film Power Control Amplifier", groupCode: "10" },
      { code: "10.4", name: "Amplifier", groupCode: "10" },
      { code: "10.5", name: "Speaker", groupCode: "10" },
      { code: "10.6", name: "Restroom", groupCode: "10" },
      { code: "10.7", name: "Film Rewinder", groupCode: "10" },
      { code: "10.8", name: "Ticket Sell Box", groupCode: "10" },
      { code: "10.9", name: "Map", groupCode: "10" },
      { code: "10.10", name: "Globe", groupCode: "10" },
      { code: "10.11", name: "Wall Pictures", groupCode: "10" },
      { code: "10.12", name: "Planning Board", groupCode: "10" },
      { code: "10.13", name: "Insect Collector", groupCode: "10" },
      { code: "10.14", name: "Balance / Scale", groupCode: "10" },
      { code: "10.15", name: "Wind Vane", groupCode: "10" },
      { code: "10.16", name: "Rain Gauge", groupCode: "10" },
      { code: "10.17", name: "Picture Stand", groupCode: "10" },
      { code: "10.18", name: "Hanger", groupCode: "10" },
      { code: "10.19", name: "Award Display - Metal Shelf", groupCode: "10" },
      { code: "10.20", name: "Brief-Case", groupCode: "10" },
      { code: "10.21", name: "Black Board", groupCode: "10" },
      { code: "10.22", name: "Communication Radio", groupCode: "10" },
      { code: "10.23", name: "Trolley", groupCode: "10" },
      { code: "10.24", name: "Wall Clock", groupCode: "10" },
      { code: "10.25", name: "Suction", groupCode: "10" },
      { code: "10.26", name: "Drum", groupCode: "10" },
      { code: "10.27", name: "Prism", groupCode: "10" },
      { code: "10.28", name: "Sprayer", groupCode: "10" },
      { code: "10.29", name: "Soil Boring", groupCode: "10" },
      { code: "10.30", name: "Lab. Inst. Stand", groupCode: "10" },
      { code: "10.31", name: "Electrical Water Pump", groupCode: "10" },
      { code: "10.32", name: "Photo Camera", groupCode: "10" },
      { code: "10.33", name: "Pontoons / Bouyous Bridge", groupCode: "10" },
      { code: "10.34", name: "Billiard Table", groupCode: "10" },
      { code: "10.35", name: "Billiard Score Recording", groupCode: "10" },
      { code: "10.36", name: "Billiard Stick Holder", groupCode: "10" },
      { code: "10.37", name: "Piano", groupCode: "10" },
      { code: "10.38", name: "Lens", groupCode: "10" },
      { code: "10.40", name: "Film Splicing Device", groupCode: "10" },
      { code: "10.41", name: "Stabilizer", groupCode: "10" },
      { code: "10.42", name: "Microfilm Reader", groupCode: "10" },
      { code: "10.43", name: "Cobas C-311 Analyzer / Turbine Moden", groupCode: "10" },
      { code: "10.44", name: "Books", groupCode: "10" },
      { code: "10.45", name: "Micrometer", groupCode: "10" },
      { code: "10.46", name: "Compass", groupCode: "10" },
      { code: "10.47", name: "Printing Machine", groupCode: "10" },
      { code: "10.48", name: "Rapido Graph", groupCode: "10" },
      { code: "10.49", name: "Spirit Level", groupCode: "10" },
      { code: "10.50", name: "Trammel Compass", groupCode: "10" },
      { code: "10.51", name: "Measuring Protractor", groupCode: "10" },
      { code: "10.52", name: "Ladder", groupCode: "10" },
      { code: "10.53", name: "Sugar Cart", groupCode: "10" },
      { code: "10.54", name: "Oxygen Cylinder", groupCode: "10" },
      { code: "10.55", name: "Wheel Barrow", groupCode: "10" },
      { code: "10.56", name: "Megaphone", groupCode: "10" },
      { code: "10.57", name: "Human Anatomical Picture", groupCode: "10" },
      { code: "10.58", name: "X-Ray Viewer Lamp / Odelca Magnifier Mirror", groupCode: "10" },
      { code: "10.60", name: "X-Ray Apparatus", groupCode: "10" },
      { code: "10.61", name: "Centrifuge", groupCode: "10" },
      { code: "10.62", name: "Microscope", groupCode: "10" },
      { code: "10.63", name: "Vitaron", groupCode: "10" },
      { code: "10.64", name: "X-Ray Film Drier Machine", groupCode: "10" },
      { code: "10.65", name: "Odelca Film Holder", groupCode: "10" },
      { code: "10.66", name: "X-Ray Chest Stand", groupCode: "10" },
      { code: "10.67", name: "X-Ray Printer", groupCode: "10" },
      { code: "10.68", name: "X-Ray Film Holder Box", groupCode: "10" },
      { code: "10.69", name: "X-Ray Timing Device / Odelca Tube", groupCode: "10" },
      { code: "10.70", name: "Odelca Film Developing Device", groupCode: "10" },
      { code: "10.71", name: "Needle Sterilizer", groupCode: "10" },
      { code: "10.72", name: "Steam Sterilizer", groupCode: "10" },
      { code: "10.73", name: "Operation Lamp", groupCode: "10" },
      { code: "10.74", name: "Weight Standard Stone", groupCode: "10" },
      { code: "10.75", name: "Fork Lift", groupCode: "10" },
      { code: "10.76", name: "Tripod", groupCode: "10" },
      { code: "10.77", name: "Stadia Meter / Distance Measuring", groupCode: "10" },
      { code: "10.79", name: "Tri-Square", groupCode: "10" },
      { code: "10.80", name: "Ground Tennis Net", groupCode: "10" },
      { code: "10.81", name: "Ground Tennis Court Roller", groupCode: "10" },
      { code: "10.82", name: "Ground Tennis Referee Seat", groupCode: "10" },
      { code: "10.83", name: "Video Deck", groupCode: "10" },
      { code: "10.84", name: "Film Reel", groupCode: "10" },
      { code: "10.85", name: "Fire Extinguisher", groupCode: "10" },
      { code: "10.86", name: "Differential Counter", groupCode: "10" },
      { code: "10.87", name: "Juice Squeezer", groupCode: "10" },
      { code: "10.88", name: "Hand Stretcher / Chair", groupCode: "10" },
      { code: "10.89", name: "Coach Bed", groupCode: "10" },
      { code: "10.90", name: "Odelca Machine & Apparatus", groupCode: "10" },
      { code: "10.91", name: "Odelca Film Drier", groupCode: "10" },
      { code: "10.92", name: "Hyundai X-Ray Machine", groupCode: "10" },
      { code: "10.93", name: "Corner Lamp", groupCode: "10" },
      { code: "10.94", name: "Overhead Projector & Screen with Stand", groupCode: "10" },
      { code: "10.95", name: "Photo Camera Stand", groupCode: "10" },
      { code: "10.97", name: "Gifco Grinder", groupCode: "10" },
      { code: "10.98", name: "Sugar Sales Box", groupCode: "10" },
      { code: "10.99", name: "Mobile Telephone", groupCode: "10" },
      { code: "10.100", name: "Detector", groupCode: "10" },
      { code: "10.101", name: "Satellite Dish", groupCode: "10" },
      { code: "10.102", name: "Notice Board", groupCode: "10" },
      { code: "10.103", name: "White Board with Stand", groupCode: "10" },
      { code: "10.104", name: "Water Bath", groupCode: "10" },
      { code: "10.105", name: "Photometer", groupCode: "10" },
      { code: "10.106", name: "Electric Charger Car / Sugar Transport", groupCode: "10" },
      { code: "10.107", name: "Bingo Machine Set", groupCode: "10" },
      { code: "10.108", name: "Multi Choice DSTV", groupCode: "10" },
      { code: "10.109", name: "Programming Controller (Ikusi) for Decoder", groupCode: "10" },
      { code: "10.110", name: "Microphone", groupCode: "10" },
      { code: "10.111", name: "Equibetor", groupCode: "10" },
      { code: "10.112", name: "Lamp Rechargeable", groupCode: "10" },
      { code: "10.113", name: "Atmolit-N", groupCode: "10" },
      { code: "10.114", name: "E.K.G. Electrocardiograph Machine", groupCode: "10" },
      { code: "10.115", name: "Ultrasound 128 BW Machine", groupCode: "10" },
      { code: "10.116", name: "Rewinder - RW 200 / VHS", groupCode: "10" },
      { code: "10.117", name: "Reader 2305", groupCode: "10" },
      { code: "10.118", name: "Washer 430 / Power", groupCode: "10" },
      { code: "10.119", name: "Epson LX-300+ Printer", groupCode: "10" },
      { code: "10.120", name: "Tekan Bottle Holder", groupCode: "10" },
      { code: "10.121", name: "Labour Photometer LP420", groupCode: "10" },
      { code: "10.122", name: "Vacuum", groupCode: "10" },
      { code: "10.123", name: "Dental Machine Swivel", groupCode: "10" },
      { code: "10.124", name: "Dental X-Ray Machine / Hematology Analyzer", groupCode: "10" },
      { code: "10.125", name: "Dental Instrument Container Swivel", groupCode: "10" },
      { code: "10.126", name: "UPS for Furnace / Voltage Regulator", groupCode: "10" },
      { code: "10.127", name: "Counting System / Movable Screen", groupCode: "10" },
      { code: "10.128", name: "Facs Court System / TV Transmission Machine", groupCode: "10" },
      { code: "10.129", name: "Chemistry Analyzer / Medical Device Machine", groupCode: "10" },
      { code: "10.131", name: "Umbrella", groupCode: "10" },
      { code: "10.132", name: "Sysmex / Genex / Cobas C-311 Dazter", groupCode: "10" },
      { code: "10.133", name: "Printer Thermal", groupCode: "10" },
      { code: "10.135", name: "Plastic Pallets", groupCode: "10" },
      { code: "10.136", name: "Electric Telephone Pole", groupCode: "10" },
      { code: "10.137", name: "Roost", groupCode: "10" },
      { code: "10.138", name: "Wireless Microscope", groupCode: "10" },
      { code: "10.139", name: "Hair Dryer Unit", groupCode: "10" },
    ],
  },
];

/** Flat lookup: itemCode -> AssetItem */
export const ITEM_BY_CODE: Record<string, AssetItem> = {};
for (const group of ASSET_GROUPS) {
  for (const item of group.items) {
    ITEM_BY_CODE[item.code] = item;
  }
}

/** Flat lookup: groupCode -> AssetGroup */
export const GROUP_BY_CODE: Record<string, AssetGroup> = {};
for (const group of ASSET_GROUPS) {
  GROUP_BY_CODE[group.code] = group;
}

/** All items as flat array */
export const ALL_ASSET_ITEMS: AssetItem[] = ASSET_GROUPS.flatMap((g) => g.items);
