# Generated by Django 5.1.4 on 2026-07-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0004_convert_legacy_house_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="inside_items",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of inside items for the house, e.g., Bed, Chair.",
                verbose_name="inside items",
            ),
        ),
    ]
