# Generated by Django 5.1.4 on 2026-07-24 12:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0005_house_inside_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("auto_allocated", "Auto Allocated"),
                            ("manual_allocated", "Manual Allocated"),
                            ("deallocated", "Deallocated"),
                            ("reallocated", "Reallocated"),
                        ],
                        max_length=30,
                        verbose_name="action",
                    ),
                ),
                (
                    "priority_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="priority score at time of action",
                    ),
                ),
                (
                    "eligible_category",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        verbose_name="eligible category at time of action",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "allocation log",
                "verbose_name_plural": "allocation logs",
                "db_table": "allocation_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScoringConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        default="Default",
                        max_length=100,
                        verbose_name="configuration name",
                    ),
                ),
                (
                    "job_grade_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=30,
                        help_text="Weight for job grade scoring (0-100).",
                        max_digits=5,
                        verbose_name="job grade weight",
                    ),
                ),
                (
                    "years_of_service_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=25,
                        help_text="Weight for years of service scoring (0-100).",
                        max_digits=5,
                        verbose_name="years of service weight",
                    ),
                ),
                (
                    "family_size_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        help_text="Weight for family size scoring (0-100).",
                        max_digits=5,
                        verbose_name="family size weight",
                    ),
                ),
                (
                    "disability_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=15,
                        help_text="Weight for disability status scoring (0-100).",
                        max_digits=5,
                        verbose_name="disability weight",
                    ),
                ),
                (
                    "fifo_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="Weight for application date (FIFO) scoring (0-100).",
                        max_digits=5,
                        verbose_name="FIFO weight",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "scoring configuration",
                "verbose_name_plural": "scoring configurations",
                "db_table": "scoring_config",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="allocated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="allocated at"
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="allocated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocated_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="allocated by",
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="allocated_house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocations",
                to="houses.house",
                verbose_name="allocated house",
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="eligible_house_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Staff", "Staff"),
                    ("A", "Type A"),
                    ("B", "Type B"),
                    ("C", "Type C"),
                    ("D", "Type D"),
                    ("E", "Type E (Barrack)"),
                ],
                help_text="Auto-determined from job grade.",
                max_length=10,
                verbose_name="eligible house category",
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="priority_score",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="priority score",
            ),
        ),
        migrations.AddIndex(
            model_name="houseapplication",
            index=models.Index(
                fields=["priority_score"], name="house_appli_priorit_0b39a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="houseapplication",
            index=models.Index(
                fields=["eligible_house_category"],
                name="house_appli_eligibl_d1e1fa_idx",
            ),
        ),
        migrations.AddField(
            model_name="allocationlog",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocation_logs",
                to="houses.houseapplication",
                verbose_name="application",
            ),
        ),
        migrations.AddField(
            model_name="allocationlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="allocationlog",
            name="house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocation_logs",
                to="houses.house",
                verbose_name="house",
            ),
        ),
        migrations.AddField(
            model_name="allocationlog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="performed by",
            ),
        ),
        migrations.AddField(
            model_name="allocationlog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="scoringconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="scoringconfig",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddIndex(
            model_name="allocationlog",
            index=models.Index(
                fields=["application"], name="allocation__applica_ad20af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="allocationlog",
            index=models.Index(fields=["house"], name="allocation__house_i_504b55_idx"),
        ),
        migrations.AddIndex(
            model_name="allocationlog",
            index=models.Index(fields=["action"], name="allocation__action_89be83_idx"),
        ),
    ]
