# Generated by Django 5.1.4 on 2026-07-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0007_house_house_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="houseapplication",
            name="position_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Permanent", "Permanent"),
                    ("Seasonal", "Seasonal"),
                    ("Half Permanent", "Half Permanent"),
                    ("PPL", "PPL"),
                ],
                default="Permanent",
                help_text="Employment type: Permanent, Seasonal, Half Permanent, or PPL.",
                max_length=20,
                verbose_name="position type",
            ),
        ),
    ]
