# Generated by Django 5.1.4 on 2026-07-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0009_add_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="allocation_category",
            field=models.CharField(
                choices=[("R", "Regular"), ("G", "Guest")],
                db_index=True,
                default="R",
                help_text="R = Regular, G = Guest.",
                max_length=1,
                verbose_name="allocation category",
            ),
        ),
    ]
