# Generated by Django 5.1.4 on 2026-07-27 11:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0010_add_allocation_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "inspection_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="inspection date",
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("Move-In", "Move-In"),
                            ("Move-Out", "Move-Out"),
                            ("Routine", "Routine"),
                            ("Damage Assessment", "Damage Assessment"),
                        ],
                        default="Routine",
                        max_length=30,
                        verbose_name="type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Passed", "Passed"),
                            ("Needs Repair", "Needs Repair"),
                            ("Failed", "Failed"),
                        ],
                        default="Passed",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "findings",
                    models.JSONField(blank=True, default=dict, verbose_name="findings"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="houses.house",
                        verbose_name="house",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="inspector",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "house inspection",
                "verbose_name_plural": "house inspections",
                "db_table": "house_inspections",
                "ordering": ["-inspection_date"],
            },
        ),
        migrations.CreateModel(
            name="HouseMaintenanceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "issue_title",
                    models.CharField(max_length=255, verbose_name="issue title"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Plumbing", "Plumbing"),
                            ("Electrical", "Electrical"),
                            ("Structural", "Structural"),
                            ("Appliance", "Appliance"),
                            ("HVAC", "HVAC"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=30,
                        verbose_name="category",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Urgent", "Urgent"),
                        ],
                        default="Medium",
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "Resolved"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Open",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="estimated cost",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resolved at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to="houses.house",
                        verbose_name="house",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reported by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "house maintenance request",
                "verbose_name_plural": "house maintenance requests",
                "db_table": "house_maintenance_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HouseNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "notification_type",
                    models.CharField(
                        default="info", max_length=50, verbose_name="type"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="is read")),
                (
                    "link",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="link"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recipient",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "house notification",
                "verbose_name_plural": "house notifications",
                "db_table": "house_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HouseTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "transfer_no",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="transfer number",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(max_length=50, verbose_name="employee ID"),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=255, verbose_name="employee name"),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="reason for transfer"),
                ),
                (
                    "priority_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="priority score",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="approved by",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "current_house",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_from",
                        to="houses.house",
                        verbose_name="current house",
                    ),
                ),
                (
                    "target_house",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_to",
                        to="houses.house",
                        verbose_name="target house",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "house transfer",
                "verbose_name_plural": "house transfers",
                "db_table": "house_transfers",
                "ordering": ["-created_at"],
            },
        ),
    ]
