# Generated by Django 5.1.4 on 2026-07-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_passwordresetotp_delete_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                    ("MANAGER", "Manager"),
                    ("FIELD_STAFF", "Field Staff"),
                    ("AUDITOR", "Auditor"),
                    ("REQUESTER", "Requester"),
                    ("APPLICANT", "Applicant"),
                ],
                db_index=True,
                default="FIELD_STAFF",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
