import { useConfirm, crudToast } from "@/lib/enterprise-feedback";
import { useEffect, useState, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { PageSkeleton } from "@/components/ui/page-skeletons";
import Breadcrumbs from "@/components/layout/Breadcrumbs";
import PageHeader from "@/components/layout/PageHeader";
import { listApplications, deleteApplication, submitApplication, type HouseApplication } from "@/services/houseApplication";

const STATUS_COLORS: Record<string, string> = {
  Draft: "bg-muted text-muted-foreground",
  Submitted: "bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300",
  "Under Review": "bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300",
  Verified: "bg-teal-100 text-teal-800 dark:bg-teal-900/40 dark:text-teal-300",
  "Waiting for Allocation": "bg-purple-100 text-purple-800 dark:bg-purple-900/40 dark:text-purple-300",
  Allocated: "bg-green-100 text-green-800 dark:bg-green-900/40 dark:text-green-300",
  Rejected: "bg-red-100 text-red-800 dark:bg-red-900/40 dark:text-red-300",
  Returned: "bg-orange-100 text-orange-800 dark:bg-orange-900/40 dark:text-orange-300",
};

export default function HouseApplicationMy() {
  const confirm = useConfirm();
  const navigate = useNavigate();
  const [applications, setApplications] = useState<HouseApplication[]>([]);
  const [loading, setLoading] = useState(true);

  const fetch = useCallback(async () => {
    try {
      setLoading(true);
      const data = await listApplications();
      setApplications(data);
    } catch (err: any) {
      toast.error(err?.message || "Failed to load applications");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetch(); }, [fetch]);

  const handleSubmit = async (id: string) => {
    try {
      await submitApplication(id);
      toast.success("Application submitted");
      fetch();
    } catch (err: any) {
      toast.error(err?.message || "Failed to submit");
    }
  };

  const handleDelete = async (id: string) => {
    const ok = await confirm({
      title: "Delete Application",
      description: "Are you sure you want to delete this housing application draft? This action cannot be undone.",
      variant: "danger",
      confirmLabel: "Delete Application",
    });
    if (!ok) return;
    try {
      await deleteApplication(id);
      crudToast.deleted("Application", "Your housing application has been deleted.");
      fetch();
    } catch (err: any) {
      crudToast.failed("delete application", err?.message);
    }
  };

  const handlePrint = (app: HouseApplication) => {
    const w = window.open("", "_blank");
    if (!w) return;
    w.document.write(`
      <html><head><title>Application ${app.application_no}</title>
      <style>body{font-family:sans-serif;padding:40px;max-width:800px;margin:auto}
      h1{font-size:20px;border-bottom:2px solid #333;padding-bottom:8px}
      table{width:100%;border-collapse:collapse;margin:16px 0}
      td{padding:8px;border-bottom:1px solid #ddd}
      td:first-child{font-weight:600;width:200px}
      .status{display:inline-block;padding:4px 12px;border-radius:999px;font-size:13px;background:#eee}
      </style></head><body>
      <h1>House Application - ${app.application_no}</h1>
      <table>
        <tr><td>Employee Name</td><td>${app.employee_name}</td></tr>
        <tr><td>Employee ID</td><td>${app.employee_id}</td></tr>
        <tr><td>National ID</td><td>${app.national_id}</td></tr>
        <tr><td>Gender</td><td>${app.gender}</td></tr>
        <tr><td>Job Position</td><td>${app.job_position}</td></tr>
        <tr><td>Job Grade</td><td>${app.job_grade}</td></tr>
        <tr><td>Years of Service</td><td>${app.years_of_service}</td></tr>
        <tr><td>Marital Status</td><td>${app.marital_status}</td></tr>
        <tr><td>Family Size</td><td>${app.family_size}</td></tr>
        <tr><td>Number of Children</td><td>${app.number_of_children}</td></tr>
        <tr><td>Requested Category</td><td>${app.requested_house_category}</td></tr>
        <tr><td>Preferred Location</td><td>${app.preferred_location}</td></tr>
        <tr><td>Status</td><td><span class="status">${app.status}</span></td></tr>
        <tr><td>Submitted At</td><td>${app.submitted_at ? new Date(app.submitted_at).toLocaleDateString() : "-"}</td></tr>
      </table>
      <p style="margin-top:24px;color:#666;font-size:12px">Generated by SAMS</p>
      </body></html>
    `);
    w.document.close();
    w.print();
  };

  if (loading) return <PageSkeleton />;

  return (
    <div className="space-y-6 pb-10">
      <Breadcrumbs items={[{ label: "House Application" }, { label: "My Applications" }]} />
      <PageHeader title="My Applications" description="View and manage your house applications" />
      <Card>
        <CardHeader><CardTitle>All Applications</CardTitle></CardHeader>
        <CardContent>
          {applications.length === 0 ? (
            <div className="py-12 text-center text-muted-foreground">
              <p>No applications yet.</p>
              <Button variant="outline" className="mt-4" onClick={() => navigate("/house-application/new")}>
                Create New Application
              </Button>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Application No.</TableHead>
                  <TableHead>Employee</TableHead>
                  <TableHead>Category</TableHead>
                  <TableHead>Submitted</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {applications.map((app) => (
                  <TableRow key={app.id}>
                    <TableCell className="font-mono text-xs">{app.application_no}</TableCell>
                    <TableCell>{app.employee_name}</TableCell>
                    <TableCell>{app.requested_house_category}</TableCell>
                    <TableCell className="text-sm text-muted-foreground">
                      {app.submitted_at ? new Date(app.submitted_at).toLocaleDateString() : "-"}
                    </TableCell>
                    <TableCell>
                      <Badge variant="outline" className={STATUS_COLORS[app.status] || ""}>
                        {app.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-1">
                        <Button size="sm" variant="ghost" onClick={() => navigate(`/house-application/status?id=${app.id}`)}>
                          View
                        </Button>
                        {(app.status === "Draft" || app.status === "Returned") && (
                          <>
                            <Button size="sm" variant="ghost" onClick={() => navigate(`/house-application/new?id=${app.id}`)}>
                              Edit
                            </Button>
                            {app.status === "Draft" && (
                              <Button size="sm" variant="ghost" onClick={() => handleSubmit(app.id)}>
                                Submit
                              </Button>
                            )}
                            <Button size="sm" variant="ghost" className="text-destructive" onClick={() => handleDelete(app.id)}>
                              Delete
                            </Button>
                          </>
                        )}
                        <Button size="sm" variant="ghost" onClick={() => handlePrint(app)}>
                          Print
                        </Button>
                        {app.supporting_document && (
                          <Button size="sm" variant="ghost" asChild>
                            <a href={app.supporting_document} target="_blank" rel="noreferrer">Doc</a>
                          </Button>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
