# Generated by Django 5.1.4 on 2026-07-03 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "house_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="house ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        db_index=True,
                        help_text="Physical address or compound name of the house.",
                        max_length=255,
                        verbose_name="location",
                    ),
                ),
                (
                    "house_type",
                    models.CharField(
                        choices=[
                            ("Staff", "Staff"),
                            ("A", "Type A"),
                            ("B", "Type B"),
                            ("C", "Type C"),
                            ("D", "Type D"),
                        ],
                        db_index=True,
                        default="Staff",
                        max_length=10,
                        verbose_name="type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        db_index=True,
                        default="Active",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Maximum number of residents this unit can hold.",
                        verbose_name="capacity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "house",
                "verbose_name_plural": "houses",
                "db_table": "houses",
                "ordering": ["house_id"],
                "indexes": [
                    models.Index(fields=["house_id"], name="houses_house_i_6206af_idx"),
                    models.Index(
                        fields=["house_type"], name="houses_house_t_9bcd79_idx"
                    ),
                    models.Index(fields=["status"], name="houses_status_08293c_idx"),
                ],
            },
        ),
    ]
