# Generated by Django 5.1.4 on 2026-07-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0006_delete_householditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="inside_items",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of items inside house: Bed, Chair, Table, Locker",
                verbose_name="inside items",
            ),
        ),
    ]
