# Generated by Django 5.1.4 on 2026-07-27 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_add_marital_status"),
        ("houses", "0009_houseinspection_housetransfer_maintenancerequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "contract_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="contract number",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "monthly_rent",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="monthly rent"
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="security deposit",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending", "Pending"),
                            ("Expired", "Expired"),
                            ("Terminated", "Terminated"),
                            ("Renewed", "Renewed"),
                        ],
                        db_index=True,
                        default="Active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "terms_conditions",
                    models.TextField(blank=True, verbose_name="terms & conditions"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rental_contracts",
                        to="houses.houseapplication",
                        verbose_name="source application",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_contracts",
                        to="houses.house",
                        verbose_name="house",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_contracts",
                        to="employees.employee",
                        verbose_name="tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "rental contract",
                "verbose_name_plural": "rental contracts",
                "db_table": "rental_contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RentalInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "invoice_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="invoice number",
                    ),
                ),
                (
                    "billing_month",
                    models.CharField(max_length=20, verbose_name="billing month"),
                ),
                ("due_date", models.DateField(verbose_name="due date")),
                (
                    "rent_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="rent amount"
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="late penalty",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="paid amount",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="balance"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Unpaid", "Unpaid"),
                            ("Partially Paid", "Partially Paid"),
                            ("Paid", "Paid"),
                            ("Overdue", "Overdue"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="Unpaid",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="houses.rentalcontract",
                        verbose_name="rental contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_invoices",
                        to="employees.employee",
                        verbose_name="tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "rental invoice",
                "verbose_name_plural": "rental invoices",
                "db_table": "rental_invoices",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="RentalPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "receipt_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="receipt number",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount paid"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Bank Transfer", "Bank Transfer"),
                            ("Cash", "Cash"),
                            ("Payroll Deduction", "Payroll Deduction"),
                            ("Mobile Money", "Mobile Money"),
                        ],
                        default="Bank Transfer",
                        max_length=30,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reference number"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="houses.rentalinvoice",
                        verbose_name="invoice",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "rental payment",
                "verbose_name_plural": "rental payments",
                "db_table": "rental_payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
