# Generated by Django 5.1.4 on 2026-08-04 05:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_add_marital_status"),
        ("houses", "0010_rentalcontract_rentalinvoice_rentalpayment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllocationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "application_no",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="application number"
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=255, verbose_name="employee name"),
                ),
                (
                    "employee_id",
                    models.CharField(max_length=50, verbose_name="employee ID"),
                ),
                (
                    "house_hid",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="house ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Allocated", "Allocated"),
                            ("Deallocated", "Deallocated"),
                            ("Transferred", "Transferred"),
                            ("Auto-Allocated", "Auto-Allocated"),
                            ("Manual Override", "Manual Override"),
                            ("Queue Joined", "Queue Joined"),
                            ("Queue Left", "Queue Left"),
                            ("Status Changed", "Status Changed"),
                        ],
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="old status"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="new status"
                    ),
                ),
                (
                    "priority_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=8,
                        verbose_name="priority score",
                    ),
                ),
                (
                    "eligible_category",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="eligible category",
                    ),
                ),
                (
                    "score_breakdown",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="score breakdown (XAI)"
                    ),
                ),
                (
                    "recommendation_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="recommendation reason"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "performed_by_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="performed by name",
                    ),
                ),
            ],
            options={
                "verbose_name": "allocation log",
                "verbose_name_plural": "allocation logs",
                "db_table": "allocation_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EligibilityRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "min_grade",
                    models.IntegerField(
                        default=0, verbose_name="minimum grade (inclusive)"
                    ),
                ),
                (
                    "max_grade",
                    models.IntegerField(
                        default=30, verbose_name="maximum grade (inclusive)"
                    ),
                ),
                (
                    "house_type",
                    models.CharField(
                        choices=[
                            ("Staff", "Staff"),
                            ("A", "Type A"),
                            ("B", "Type B"),
                            ("C", "Type C"),
                            ("D", "Type D"),
                            ("E", "Type E (Barrack)"),
                        ],
                        max_length=10,
                        verbose_name="house type",
                    ),
                ),
                (
                    "gender_eligibility",
                    models.CharField(
                        choices=[
                            ("Both", "Both"),
                            ("Male", "Male Only"),
                            ("Female", "Female Only"),
                        ],
                        default="Both",
                        max_length=10,
                        verbose_name="gender eligibility",
                    ),
                ),
                (
                    "requires_family",
                    models.BooleanField(
                        default=False,
                        help_text="If true, only married employees qualify",
                        verbose_name="requires family (married)",
                    ),
                ),
                (
                    "min_family_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="minimum family size"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower = evaluated first",
                        verbose_name="evaluation order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="active"
                    ),
                ),
            ],
            options={
                "verbose_name": "eligibility rule",
                "verbose_name_plural": "eligibility rules",
                "db_table": "eligibility_rules",
                "ordering": ["priority", "min_grade"],
            },
        ),
        migrations.CreateModel(
            name="ScoringConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        default="Default Config",
                        max_length=100,
                        verbose_name="configuration name",
                    ),
                ),
                (
                    "job_grade_weight",
                    models.PositiveIntegerField(
                        default=30, verbose_name="job grade weight %"
                    ),
                ),
                (
                    "years_of_service_weight",
                    models.PositiveIntegerField(
                        default=25, verbose_name="years of service weight %"
                    ),
                ),
                (
                    "family_size_weight",
                    models.PositiveIntegerField(
                        default=20, verbose_name="family size weight %"
                    ),
                ),
                (
                    "disability_weight",
                    models.PositiveIntegerField(
                        default=10, verbose_name="disability priority weight %"
                    ),
                ),
                (
                    "fifo_weight",
                    models.PositiveIntegerField(
                        default=15, verbose_name="FIFO / waiting time weight %"
                    ),
                ),
                (
                    "marital_status_weight",
                    models.PositiveIntegerField(
                        default=0, verbose_name="marital status weight %"
                    ),
                ),
                (
                    "employment_type_weight",
                    models.PositiveIntegerField(
                        default=0, verbose_name="employment type weight %"
                    ),
                ),
                (
                    "medical_priority_weight",
                    models.PositiveIntegerField(
                        default=0, verbose_name="medical priority weight %"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="active config"
                    ),
                ),
            ],
            options={
                "verbose_name": "scoring config",
                "verbose_name_plural": "scoring configs",
                "db_table": "scoring_configs",
                "ordering": ["-is_active", "-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="houseinspection",
            options={"ordering": ["-scheduled_date"]},
        ),
        migrations.AlterModelOptions(
            name="housetransfer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="maintenancerequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="rentalcontract",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="rentalinvoice",
            options={"ordering": ["-due_date"]},
        ),
        migrations.AlterModelOptions(
            name="rentalpayment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="allocated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="allocated at"
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="allocated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocated_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="allocated_house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocations",
                to="houses.house",
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="allocation_notes",
            field=models.TextField(blank=True, verbose_name="allocation notes"),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="deallocation_reason",
            field=models.TextField(blank=True, verbose_name="deallocation reason"),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="eligible_house_category",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                verbose_name="eligible house category",
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="priority_score",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=8, verbose_name="priority score"
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="queue_position",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="queue position"
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="score_breakdown",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="score breakdown (XAI)"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="capacity",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="capacity"),
        ),
        migrations.AlterField(
            model_name="house",
            name="inside_items",
            field=models.JSONField(
                blank=True, default=list, verbose_name="inside items"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="location",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="location"
            ),
        ),
        migrations.AlterField(
            model_name="houseapplication",
            name="emp_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="house_applications",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="houseapplication",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="house_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="houseapplication",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="houseinspection",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspections",
                to="houses.house",
            ),
        ),
        migrations.AlterField(
            model_name="houseinspection",
            name="inspection_type",
            field=models.CharField(
                choices=[
                    ("Move-In", "Move-In"),
                    ("Move-Out", "Move-Out"),
                    ("Routine", "Routine"),
                    ("Damage Assessment", "Damage Assessment"),
                ],
                default="Routine",
                max_length=30,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="houseinspection",
            name="inspector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conducted_inspections",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="housetransfer",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="housetransfer",
            name="current_house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_from",
                to="houses.house",
            ),
        ),
        migrations.AlterField(
            model_name="housetransfer",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="house_transfers",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="housetransfer",
            name="target_house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_to",
                to="houses.house",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to="houses.house",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="rentalcontract",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rental_contracts",
                to="houses.houseapplication",
            ),
        ),
        migrations.AlterField(
            model_name="rentalcontract",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_contracts",
                to="houses.house",
            ),
        ),
        migrations.AlterField(
            model_name="rentalcontract",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_contracts",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="rentalinvoice",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="houses.rentalcontract",
            ),
        ),
        migrations.AlterField(
            model_name="rentalinvoice",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_invoices",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="rentalpayment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="houses.rentalinvoice",
            ),
        ),
        migrations.AlterField(
            model_name="rentalpayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Bank Transfer", "Bank Transfer"),
                    ("Cash", "Cash"),
                    ("Payroll Deduction", "Payroll Deduction"),
                    ("Mobile Money", "Mobile Money"),
                ],
                default="Bank Transfer",
                max_length=30,
                verbose_name="method",
            ),
        ),
        migrations.AlterField(
            model_name="rentalpayment",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="houseapplication",
            index=models.Index(
                fields=["priority_score"], name="house_appli_priorit_0b39a2_idx"
            ),
        ),
        migrations.AddField(
            model_name="allocationlog",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocation_logs",
                to="houses.houseapplication",
            ),
        ),
        migrations.AddField(
            model_name="allocationlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="allocationlog",
            name="house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocation_logs",
                to="houses.house",
            ),
        ),
        migrations.AddField(
            model_name="allocationlog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="allocationlog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="eligibilityrule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="eligibilityrule",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="scoringconfig",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="scoringconfig",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddIndex(
            model_name="allocationlog",
            index=models.Index(
                fields=["application"], name="allocation__applica_ad20af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="allocationlog",
            index=models.Index(fields=["action"], name="allocation__action_89be83_idx"),
        ),
        migrations.AddIndex(
            model_name="allocationlog",
            index=models.Index(
                fields=["employee_id"], name="allocation__employe_5d9b01_idx"
            ),
        ),
    ]
