# Generated by Django 5.1.4 on 2026-08-05 06:20

from django.db import migrations, models


def backfill_house_number(apps, schema_editor):
    """
    Backfill house_number for existing houses.
    Groups them by house_type, ordered by house_id ascending, then assigns
    <type><n> (A1, A2, B1, Staff1 …). Prefixes: Staff=S, A–E use the letter.
    """
    House = apps.get_model("houses", "House")
    from collections import defaultdict

    prefix_for = {"Staff": "S", "A": "A", "B": "B", "C": "C", "D": "D", "E": "E"}
    by_type = defaultdict(list)
    for house in House.objects.all().order_by("house_id"):
        by_type[house.house_type].append(house)

    for house_type, houses in by_type.items():
        prefix = prefix_for.get(house_type, (house_type[:1].upper() if house_type else "X"))
        for idx, house in enumerate(houses, start=1):
            if not house.house_number:
                house.house_number = f"{prefix}{idx}"
                house.save(update_fields=["house_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0011_add_allocation_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="allocation_category",
            field=models.CharField(
                choices=[("R", "Regular"), ("G", "Guest")],
                db_index=True,
                default="R",
                help_text="R = Regular, G = Guest.",
                max_length=1,
                verbose_name="allocation category",
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="house_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Auto-generated sequential number per house type, e.g. A1, B3, Staff2.",
                max_length=20,
                verbose_name="house number",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Permanent", "Permanent"),
                    ("Semi Permanent", "Semi Permanent"),
                    ("Seasonal", "Seasonal"),
                ],
                default="Permanent",
                max_length=20,
                verbose_name="job type",
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="position_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Permanent", "Permanent"),
                    ("Seasonal", "Seasonal"),
                    ("Half Permanent", "Half Permanent"),
                    ("PPL", "PPL"),
                ],
                default="Permanent",
                help_text="Employment type: Permanent, Seasonal, Half Permanent, or PPL.",
                max_length=20,
                verbose_name="position type",
            ),
        ),
        migrations.RunPython(backfill_house_number, migrations.RunPython.noop),
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX IF NOT EXISTS houses_house_number_uniq
                    ON houses (house_number);
                CREATE INDEX IF NOT EXISTS houses_house_number_idx
                    ON houses (house_number);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS houses_house_number_uniq;
                DROP INDEX IF EXISTS houses_house_number_idx;
            """,
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="house",
                    name="house_number",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Auto-generated sequential number per house type, e.g. A1, B3, Staff2.",
                        max_length=20,
                        unique=True,
                        verbose_name="house number",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
