# Generated by Django 5.1.4 on 2026-08-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0012_house_allocation_category_house_house_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseNumberGenerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        db_index=True,
                        help_text="The prefix for the house category (e.g., 'S', 'A', 'B')",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "last_sequence",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The last used sequential number for this prefix",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True,
                        help_text="The display name of the category (e.g., 'Staff', 'Type A')",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "House Number Generator",
                "verbose_name_plural": "House Number Generators",
                "db_table": "house_number_generators",
                "ordering": ["prefix"],
                "indexes": [
                    models.Index(
                        fields=["prefix"], name="house_numbe_prefix_dcc291_idx"
                    ),
                    models.Index(
                        fields=["category"], name="house_numbe_categor_bc7c0c_idx"
                    ),
                ],
            },
        ),
    ]
