# Generated by Django 5.1.4 on 2026-08-11 04:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_job_type_employee_names"),
        ("houses", "0013_housenumbergenerator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="houseapplication",
            name="allocation_confidence",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Confidence (0-100) of the current/last allocation recommendation.",
                max_digits=6,
                verbose_name="allocation confidence",
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="eligibility_analysis",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Per-rule eligibility breakdown: {rule, house_type, passed, reason}.",
                verbose_name="eligibility analysis (XAI)",
            ),
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "allocation_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="allocation number",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(max_length=50, verbose_name="employee ID"),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=255, verbose_name="employee name"),
                ),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[
                            ("Auto", "Auto"),
                            ("Manual", "Manual"),
                            ("Override", "Override"),
                        ],
                        db_index=True,
                        default="Manual",
                        max_length=20,
                        verbose_name="allocation type",
                    ),
                ),
                (
                    "priority_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=8,
                        verbose_name="priority score",
                    ),
                ),
                (
                    "recommendation_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=8,
                        verbose_name="house compatibility score",
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=6,
                        verbose_name="allocation confidence",
                    ),
                ),
                (
                    "recommendation_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="recommendation reason"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Terminated", "Terminated"),
                            ("Reallocated", "Reallocated"),
                        ],
                        db_index=True,
                        default="Active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "occupancy_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Occupied", "Occupied"),
                            ("Vacated", "Vacated"),
                        ],
                        default="Pending",
                        max_length=20,
                        verbose_name="occupancy status",
                    ),
                ),
                (
                    "allocated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="allocated at"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="effective date"
                    ),
                ),
                (
                    "override_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="override reason"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="notes"),
                ),
                (
                    "terminated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="terminated at"
                    ),
                ),
                (
                    "termination_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="termination reason"
                    ),
                ),
                (
                    "allocated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocation_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_records",
                        to="houses.houseapplication",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "emp_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="house_allocations",
                        to="employees.employee",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_records",
                        to="houses.house",
                    ),
                ),
                (
                    "previous_allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="successors",
                        to="houses.allocation",
                    ),
                ),
                (
                    "terminated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminated_allocation_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "allocation",
                "verbose_name_plural": "allocations",
                "db_table": "allocations",
                "ordering": ["-allocated_at"],
                "indexes": [
                    models.Index(
                        fields=["house", "status"],
                        name="allocations_house_i_394b09_idx",
                    ),
                    models.Index(
                        fields=["application", "status"],
                        name="allocations_applica_ae355b_idx",
                    ),
                    models.Index(
                        fields=["employee_id", "status"],
                        name="allocations_employe_510ba1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HouseAuditTrail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Submitted", "Submitted"),
                            ("Review Started", "Review Started"),
                            ("Verified", "Verified"),
                            ("Rejected", "Rejected"),
                            ("Returned", "Returned"),
                            ("Score Recalculated", "Score Recalculated"),
                            ("Opportunities Generated", "Opportunities Generated"),
                            ("Opportunities Ranked", "Opportunities Ranked"),
                            ("Auto-Allocated", "Auto-Allocated"),
                            ("Manually Allocated", "Manually Allocated"),
                            ("Override Allocated", "Override Allocated"),
                            ("Deallocated", "Deallocated"),
                            ("Allocation Terminated", "Allocation Terminated"),
                            ("Reallocated", "Reallocated"),
                            ("Transferred", "Transferred"),
                            ("Status Changed", "Status Changed"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="action",
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="actor name",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="old status"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="new status"
                    ),
                ),
                (
                    "detail",
                    models.JSONField(blank=True, default=dict, verbose_name="detail"),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="note")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="house_audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_trail",
                        to="houses.houseapplication",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "house audit entry",
                "verbose_name_plural": "house audit trail",
                "db_table": "house_audit_trail",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["application", "-created_at"],
                        name="house_audit_applica_6f233d_idx",
                    ),
                    models.Index(
                        fields=["action"], name="house_audit_action_4345f7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HouseOpportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "eligible_category",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="eligible category",
                    ),
                ),
                (
                    "compatibility_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=8,
                        verbose_name="compatibility score",
                    ),
                ),
                (
                    "priority_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=8,
                        verbose_name="applicant priority score",
                    ),
                ),
                (
                    "match_reasons",
                    models.JSONField(
                        blank=True, default=list, verbose_name="match reasons (XAI)"
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("Recommended", "Recommended"),
                            ("Alternative", "Alternative"),
                            ("Not Suitable", "Not Suitable"),
                        ],
                        db_index=True,
                        default="Alternative",
                        max_length=20,
                        verbose_name="recommendation",
                    ),
                ),
                (
                    "recommendation_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="recommendation reason"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Generated", "Generated"),
                            ("Eligible", "Eligible"),
                            ("Ranked", "Ranked"),
                            ("Recommended", "Recommended"),
                            ("Selected", "Selected"),
                            ("Allocated", "Allocated"),
                            ("Rejected", "Rejected"),
                            ("Expired", "Expired"),
                            ("Unavailable", "Unavailable"),
                        ],
                        db_index=True,
                        default="Generated",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="rank in shortlist"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="notes"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="houses.houseapplication",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="houses.house",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "house opportunity",
                "verbose_name_plural": "house opportunities",
                "db_table": "house_opportunities",
                "ordering": ["rank", "-compatibility_score", "house__house_id"],
                "indexes": [
                    models.Index(
                        fields=["application", "status"],
                        name="house_oppor_applica_26ef43_idx",
                    ),
                    models.Index(
                        fields=["house", "status"],
                        name="house_oppor_house_i_6685d3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "house"),
                        name="uniq_application_house_opportunity",
                    )
                ],
            },
        ),
    ]
