# Generated by Django 6.1 on 2026-08-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0015_backfill_allocations"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="r1_notes",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R1 notes"
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="r1_occupant_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="R1 occupant employee ID",
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="r1_occupant_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R1 occupant"
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="r1_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Vacant", "Vacant"),
                    ("Occupied", "Occupied"),
                    ("Reserved", "Reserved"),
                    ("Maintenance", "Under Maintenance"),
                ],
                default="Vacant",
                max_length=20,
                verbose_name="R1 status",
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="r2_notes",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R2 notes"
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="r2_occupant_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="R2 occupant employee ID",
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="r2_occupant_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R2 occupant"
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="r2_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Vacant", "Vacant"),
                    ("Occupied", "Occupied"),
                    ("Reserved", "Reserved"),
                    ("Maintenance", "Under Maintenance"),
                ],
                default="Vacant",
                max_length=20,
                verbose_name="R2 status",
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="r3_notes",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R3 notes"
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="r3_occupant_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="R3 occupant employee ID",
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="r3_occupant_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R3 occupant"
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="r3_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Vacant", "Vacant"),
                    ("Occupied", "Occupied"),
                    ("Reserved", "Reserved"),
                    ("Maintenance", "Under Maintenance"),
                ],
                default="Vacant",
                max_length=20,
                verbose_name="R3 status",
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="room_count",
            field=models.PositiveSmallIntegerField(
                default=1, editable=False, verbose_name="room count"
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="room_labels",
            field=models.JSONField(
                blank=True, default=list, editable=False, verbose_name="room labels"
            ),
        ),
    ]
