# Generated by Django 6.1 on 2026-08-15 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0017_backfill_room_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="houseopportunity",
            name="uniq_application_house_opportunity",
        ),
        migrations.AddField(
            model_name="allocation",
            name="allocation_unit_type",
            field=models.CharField(
                choices=[
                    ("ROOM_ALLOCATION", "Room (single occupant)"),
                    ("HOUSE_ALLOCATION", "Whole house (family)"),
                ],
                db_index=True,
                default="HOUSE_ALLOCATION",
                help_text="ROOM_ALLOCATION for single occupants, HOUSE_ALLOCATION for married/families.",
                max_length=20,
                verbose_name="allocation unit",
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="family_size",
            field=models.PositiveIntegerField(default=1, verbose_name="family size"),
        ),
        migrations.AddField(
            model_name="allocation",
            name="marital_status",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="marital status"
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="room_index",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="room index"
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="room_label",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="room label"
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="room_number",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="room number"
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="room_status",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="room status at allocation",
            ),
        ),
        migrations.AddField(
            model_name="allocationlog",
            name="allocation_unit_type",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="allocation unit"
            ),
        ),
        migrations.AddField(
            model_name="allocationlog",
            name="room_label",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="room label"
            ),
        ),
        migrations.AddField(
            model_name="allocationlog",
            name="room_number",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="room number"
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="allocated_room_label",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="allocated room label",
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="allocated_room_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="allocated room number",
            ),
        ),
        migrations.AddField(
            model_name="houseapplication",
            name="allocation_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ROOM_ALLOCATION", "Room allocation (single applicant)"),
                    ("HOUSE_ALLOCATION", "Whole house allocation (family)"),
                ],
                db_index=True,
                default="",
                help_text="ROOM_ALLOCATION for single applicants (family size 1), HOUSE_ALLOCATION for married/families (family size ≥ 2).",
                max_length=20,
                verbose_name="allocation mode",
            ),
        ),
        migrations.AddField(
            model_name="houseopportunity",
            name="allocation_mode",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=20,
                verbose_name="allocation mode",
            ),
        ),
        migrations.AddField(
            model_name="houseopportunity",
            name="room_label",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="room label"
            ),
        ),
        migrations.AddField(
            model_name="houseopportunity",
            name="room_number",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="room number"
            ),
        ),
        migrations.AddConstraint(
            model_name="houseopportunity",
            constraint=models.UniqueConstraint(
                fields=("application", "house", "room_label"),
                name="uniq_application_house_room_opportunity",
            ),
        ),
    ]
