# Generated by Django 5.1.4 on 2026-08-17 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0019_backfill_allocation_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseHandoverReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "doc_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Auto-generated: HHR-0001 format.",
                        max_length=20,
                        unique=True,
                        verbose_name="document number",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(max_length=50, verbose_name="employee ID"),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=255, verbose_name="employee name"),
                ),
                (
                    "job_position",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="job position",
                    ),
                ),
                (
                    "job_grade",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="job grade"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="department",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="national ID",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="marital status",
                    ),
                ),
                (
                    "family_size",
                    models.PositiveIntegerField(default=1, verbose_name="family size"),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="house number",
                    ),
                ),
                (
                    "house_type",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="house type"
                    ),
                ),
                (
                    "house_location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="house location",
                    ),
                ),
                (
                    "room_count",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="room count"
                    ),
                ),
                (
                    "allocation_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="allocation number",
                    ),
                ),
                (
                    "application_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="application number",
                    ),
                ),
                (
                    "allocation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="allocation date"
                    ),
                ),
                (
                    "inspection_electrical",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="2.1 ኤሌክትሪክ ክፍል (electrical findings)",
                    ),
                ),
                (
                    "inspection_structural",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="2.2 የሕንፃ ክፍል (structural findings)",
                    ),
                ),
                (
                    "inspection_water",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="2.3 የውሃ ክፍል (water findings)",
                    ),
                ),
                (
                    "inspection_admin",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="2.4 የቤት አስተዳደር (admin/management findings)",
                    ),
                ),
                (
                    "committee_members",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of up to 4 committee member names.",
                        verbose_name="committee members",
                    ),
                ),
                (
                    "doc_status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Active", "Active"),
                            ("Voided", "Voided"),
                        ],
                        db_index=True,
                        default="Active",
                        max_length=10,
                        verbose_name="document status",
                    ),
                ),
                (
                    "generated_date",
                    models.DateField(auto_now_add=True, verbose_name="generated date"),
                ),
                (
                    "generated_by_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="generated by name",
                    ),
                ),
                (
                    "first_printed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="first printed at"
                    ),
                ),
                (
                    "last_printed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last printed at"
                    ),
                ),
                (
                    "printed_by_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="last printed by name",
                    ),
                ),
                (
                    "reprint_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="reprint count"
                    ),
                ),
                (
                    "audit_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Chronological list of print/reprint events.",
                        verbose_name="audit history",
                    ),
                ),
                (
                    "allocation",
                    models.OneToOneField(
                        help_text="The allocation this receipt covers.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handover_receipt",
                        to="houses.allocation",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handover_receipts",
                        to="houses.houseapplication",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_handover_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handover_receipts",
                        to="houses.house",
                    ),
                ),
                (
                    "printed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="printed_handover_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "house handover receipt",
                "verbose_name_plural": "house handover receipts",
                "db_table": "house_handover_receipts",
                "ordering": ["-generated_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["allocation"], name="house_hando_allocat_415cb2_idx"
                    ),
                    models.Index(
                        fields=["employee_id"], name="house_hando_employe_37ddd9_idx"
                    ),
                    models.Index(
                        fields=["doc_number"], name="house_hando_doc_num_0c5755_idx"
                    ),
                    models.Index(
                        fields=["doc_status"], name="house_hando_doc_sta_ecc5f2_idx"
                    ),
                ],
            },
        ),
    ]
