# Generated by Django 5.1.4 on 2026-08-18 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0020_househandoverreceipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminationCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="case code",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="case name")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Transfer", "Changed House / Transfer"),
                            ("Retirement", "Retirement"),
                            ("Release", "Release From Factory Employment"),
                            ("Voluntary", "Voluntary Surrender"),
                            ("Disciplinary", "Disciplinary Action"),
                            ("Other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "requires_inspection",
                    models.CharField(
                        choices=[
                            ("Always", "Always Required"),
                            ("Conditional", "Conditional"),
                            ("Never", "Not Required"),
                        ],
                        default="Always",
                        max_length=20,
                        verbose_name="inspection requirement",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(default=True, verbose_name="requires approval"),
                ),
                (
                    "requires_documents",
                    models.BooleanField(
                        default=False, verbose_name="requires supporting documents"
                    ),
                ),
                (
                    "allowed_employment_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Employment types this case applies to. Empty = all types.",
                        verbose_name="allowed employment types",
                    ),
                ),
                (
                    "auto_verify_employment",
                    models.BooleanField(
                        default=True,
                        help_text="When true, the system checks employee employment status matches the case.",
                        verbose_name="auto-verify employment status",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, verbose_name="evaluation order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="active"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "termination case",
                "verbose_name_plural": "termination cases",
                "db_table": "termination_cases",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="TerminationTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "termination_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="termination number",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(max_length=50, verbose_name="employee ID"),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=255, verbose_name="employee name"),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="house number",
                    ),
                ),
                (
                    "house_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="house category",
                    ),
                ),
                (
                    "room_label",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="room label"
                    ),
                ),
                (
                    "termination_reason",
                    models.TextField(verbose_name="termination reason"),
                ),
                ("effective_date", models.DateField(verbose_name="effective date")),
                (
                    "requested_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="requested date"
                    ),
                ),
                (
                    "house_release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="house release date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "handover_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Waived", "Waived"),
                        ],
                        default="Pending",
                        max_length=20,
                        verbose_name="handover status",
                    ),
                ),
                (
                    "inspection_status",
                    models.CharField(
                        choices=[
                            ("Not Required", "Not Required"),
                            ("Scheduled", "Scheduled"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Waived", "Waived"),
                        ],
                        default="Not Required",
                        max_length=20,
                        verbose_name="inspection status",
                    ),
                ),
                (
                    "damage_assessment",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="damage assessment"
                    ),
                ),
                (
                    "outstanding_issues",
                    models.TextField(
                        blank=True, default="", verbose_name="outstanding issues"
                    ),
                ),
                (
                    "damage_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        max_length=10,
                        verbose_name="damage costs",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                        max_length=20,
                        verbose_name="approval status",
                    ),
                ),
                (
                    "approval_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approval date"
                    ),
                ),
                (
                    "approval_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="approval notes"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, default="", verbose_name="remarks"),
                ),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="termination_docs/",
                        verbose_name="supporting document",
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="termination_transactions",
                        to="houses.allocation",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="termination_transactions",
                        to="houses.houseapplication",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_terminations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="houses.terminationcase",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="termination_transactions",
                        to="houses.house",
                    ),
                ),
                (
                    "target_allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminated_from_transfer",
                        to="houses.allocation",
                        verbose_name="new allocation (transfer)",
                    ),
                ),
                (
                    "target_house",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="termination_transfers_to",
                        to="houses.house",
                        verbose_name="target house (transfer)",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "termination transaction",
                "verbose_name_plural": "termination transactions",
                "db_table": "termination_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["allocation", "status"],
                        name="termination_allocat_62f1e4_idx",
                    ),
                    models.Index(
                        fields=["employee_id", "status"],
                        name="termination_employe_8ea456_idx",
                    ),
                    models.Index(
                        fields=["case", "status"], name="termination_case_id_cc9b9f_idx"
                    ),
                    models.Index(
                        fields=["status"], name="termination_status_831eae_idx"
                    ),
                ],
            },
        ),
    ]
