# Generated by Django 5.1.4 on 2026-08-18 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0021_terminationcase_terminationtransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="terminationtransaction",
            name="authorization_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Secure, non-predictable code required to execute the termination.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="termination authorization code",
            ),
        ),
        migrations.AddField(
            model_name="terminationtransaction",
            name="code_generated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="code generated at"
            ),
        ),
        migrations.AddField(
            model_name="terminationtransaction",
            name="code_generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_term_codes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="code generated by",
            ),
        ),
        migrations.AddField(
            model_name="terminationtransaction",
            name="code_verified",
            field=models.BooleanField(default=False, verbose_name="code verified"),
        ),
        migrations.AddField(
            model_name="terminationtransaction",
            name="code_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="code verified at"
            ),
        ),
        migrations.AddField(
            model_name="terminationtransaction",
            name="code_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_term_codes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="code verified by",
            ),
        ),
        migrations.AddField(
            model_name="terminationtransaction",
            name="handover_completed",
            field=models.BooleanField(default=False, verbose_name="handover completed"),
        ),
        migrations.AddField(
            model_name="terminationtransaction",
            name="inspection_baseline",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of house inspection/health status at termination creation time.",
                verbose_name="inspection baseline snapshot",
            ),
        ),
        migrations.AddField(
            model_name="terminationtransaction",
            name="inspection_discrepancies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of discrepancies between allocation baseline and current house status.",
                verbose_name="inspection discrepancies",
            ),
        ),
        migrations.AddField(
            model_name="terminationtransaction",
            name="issues_resolved",
            field=models.BooleanField(
                default=False, verbose_name="all issues resolved"
            ),
        ),
    ]
