# Generated by Django 5.1.4 on 2026-08-18 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0022_terminationtransaction_authorization_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="houseinspection",
            name="employee_id",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="employee ID"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="employee_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="employee name"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="estimated_repair_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="estimated repair cost",
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="house_location",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="house location"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="house_number",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="house number"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="house_type",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="house type"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="overall_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Excellent", "Excellent"),
                    ("Good", "Good"),
                    ("Fair", "Fair"),
                    ("Poor", "Poor"),
                    ("Critical", "Critical"),
                ],
                default="",
                max_length=20,
                verbose_name="overall condition",
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="repair_required",
            field=models.BooleanField(default=False, verbose_name="repair required"),
        ),
        migrations.AlterField(
            model_name="houseinspection",
            name="inspection_type",
            field=models.CharField(
                choices=[
                    ("Move-In", "Move-In"),
                    ("Move-Out", "Move-Out"),
                    ("Routine", "Routine"),
                    ("Damage Assessment", "Damage Assessment"),
                    ("Post-Occupancy", "Post-Occupancy"),
                ],
                default="Routine",
                max_length=30,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="houseinspection",
            name="status",
            field=models.CharField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Scheduled",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="PostInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("Move-Out", "Move-Out"),
                            ("Post-Occupancy", "Post-Occupancy"),
                            ("Pre-Termination", "Pre-Termination"),
                            ("Damage Assessment", "Damage Assessment"),
                        ],
                        default="Pre-Termination",
                        max_length=30,
                        verbose_name="type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Scheduled",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("scheduled_date", models.DateTimeField(verbose_name="scheduled date")),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed date"
                    ),
                ),
                ("findings", models.TextField(blank=True, verbose_name="findings")),
                (
                    "damage_costs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="damage costs",
                    ),
                ),
                (
                    "checklist_results",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="checklist results"
                    ),
                ),
                (
                    "house_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="house number",
                    ),
                ),
                (
                    "house_location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="house location",
                    ),
                ),
                (
                    "house_type",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="house type"
                    ),
                ),
                (
                    "overall_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Excellent", "Excellent"),
                            ("Good", "Good"),
                            ("Fair", "Fair"),
                            ("Poor", "Poor"),
                            ("Critical", "Critical"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="overall condition",
                    ),
                ),
                (
                    "repair_required",
                    models.BooleanField(default=False, verbose_name="repair required"),
                ),
                (
                    "estimated_repair_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="estimated repair cost",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="employee ID",
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="employee name",
                    ),
                ),
                (
                    "allocation_status_snapshot",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Snapshot of the linked allocation's status when inspection was created.",
                        max_length=20,
                        verbose_name="allocation status at inspection",
                    ),
                ),
                (
                    "house_status_snapshot",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Snapshot of the house's status when inspection was created.",
                        max_length=20,
                        verbose_name="house status at inspection",
                    ),
                ),
                (
                    "allocation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="post_inspections",
                        to="houses.allocation",
                        verbose_name="linked allocation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_inspections",
                        to="houses.house",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_post_inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "post inspection",
                "verbose_name_plural": "post inspections",
                "db_table": "house_post_inspections",
                "ordering": ["-scheduled_date"],
                "indexes": [
                    models.Index(
                        fields=["house", "status"],
                        name="house_post__house_i_a8f316_idx",
                    ),
                    models.Index(
                        fields=["employee_id", "status"],
                        name="house_post__employe_ac915d_idx",
                    ),
                ],
            },
        ),
    ]
