# Generated by Django 5.1.4 on 2026-08-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0023_post_inspection_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="houseinspection",
            name="allocation_category",
            field=models.CharField(
                blank=True,
                choices=[("R", "Regular"), ("G", "Guest")],
                default="R",
                max_length=1,
                verbose_name="allocation category",
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="capacity",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="capacity"),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="damaged_bulb",
            field=models.BooleanField(default=False, verbose_name="damaged bulb"),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="damaged_door",
            field=models.BooleanField(default=False, verbose_name="damaged door"),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="damaged_switch",
            field=models.BooleanField(default=False, verbose_name="damaged switch"),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="damaged_walls",
            field=models.BooleanField(default=False, verbose_name="damaged walls"),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="damaged_water",
            field=models.BooleanField(default=False, verbose_name="damaged water"),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="damaged_windows",
            field=models.BooleanField(default=False, verbose_name="damaged windows"),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="house_hid",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="house HID"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="inside_items",
            field=models.JSONField(
                blank=True, default=list, verbose_name="inside items"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="r1_notes",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R1 notes"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="r1_occupant_id",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="R1 occupant ID"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="r1_occupant_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R1 occupant name"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="r1_status",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="R1 status"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="r2_notes",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R2 notes"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="r2_occupant_id",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="R2 occupant ID"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="r2_occupant_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R2 occupant name"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="r2_status",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="R2 status"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="r3_notes",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R3 notes"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="r3_occupant_id",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="R3 occupant ID"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="r3_occupant_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R3 occupant name"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="r3_status",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="R3 status"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="room_count",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="room count"
            ),
        ),
        migrations.AddField(
            model_name="houseinspection",
            name="room_labels",
            field=models.JSONField(
                blank=True, default=list, verbose_name="room labels"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="allocation_category",
            field=models.CharField(
                blank=True,
                choices=[("R", "Regular"), ("G", "Guest")],
                default="R",
                max_length=1,
                verbose_name="allocation category",
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="capacity",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="capacity"),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="damaged_bulb",
            field=models.BooleanField(default=False, verbose_name="damaged bulb"),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="damaged_door",
            field=models.BooleanField(default=False, verbose_name="damaged door"),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="damaged_switch",
            field=models.BooleanField(default=False, verbose_name="damaged switch"),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="damaged_walls",
            field=models.BooleanField(default=False, verbose_name="damaged walls"),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="damaged_water",
            field=models.BooleanField(default=False, verbose_name="damaged water"),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="damaged_windows",
            field=models.BooleanField(default=False, verbose_name="damaged windows"),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="house_hid",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="house HID"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="inside_items",
            field=models.JSONField(
                blank=True, default=list, verbose_name="inside items"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="r1_notes",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R1 notes"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="r1_occupant_id",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="R1 occupant ID"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="r1_occupant_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R1 occupant name"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="r1_status",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="R1 status"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="r2_notes",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R2 notes"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="r2_occupant_id",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="R2 occupant ID"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="r2_occupant_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R2 occupant name"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="r2_status",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="R2 status"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="r3_notes",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R3 notes"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="r3_occupant_id",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="R3 occupant ID"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="r3_occupant_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="R3 occupant name"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="r3_status",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="R3 status"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="room_count",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="room count"
            ),
        ),
        migrations.AddField(
            model_name="postinspection",
            name="room_labels",
            field=models.JSONField(
                blank=True, default=list, verbose_name="room labels"
            ),
        ),
    ]
