# Generated by Django 5.1.4 on 2026-08-19 04:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0024_inspection_full_house_parity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRequestLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Submitted", "Submitted"),
                            ("Received", "Received"),
                            ("Assigned", "Assigned"),
                            ("Status Change", "Status Change"),
                            ("Note Added", "Note Added"),
                            ("Rejected", "Rejected"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                            ("Cost Updated", "Cost Updated"),
                        ],
                        max_length=20,
                        verbose_name="event type",
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="actor name",
                    ),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, default="", verbose_name="old value"),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, default="", verbose_name="new value"),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="note")),
            ],
            options={
                "db_table": "maintenance_request_logs",
                "ordering": ["created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="cost",
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="actual_cost",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="actual cost"
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="category",
            field=models.CharField(
                choices=[
                    ("Plumbing", "Plumbing"),
                    ("Electrical", "Electrical"),
                    ("Structural", "Structural"),
                    ("Roofing", "Roofing"),
                    ("Painting", "Painting"),
                    ("Flooring", "Flooring"),
                    ("Door & Window", "Door & Window"),
                    ("Water Supply", "Water Supply"),
                    ("Drainage", "Drainage"),
                    ("General", "General Repair"),
                    ("Other", "Other"),
                ],
                default="General",
                max_length=30,
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="civil_work_assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cw_assigned_maintenance_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="civil work assigned to",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="civil_work_notes",
            field=models.TextField(
                blank=True, default="", verbose_name="civil work notes"
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="completion_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="completion date"
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="estimated_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="estimated cost",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="received_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="received at"
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_maintenance_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="received by",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="rejection_reason",
            field=models.TextField(
                blank=True, default="", verbose_name="rejection reason"
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="resolution_notes",
            field=models.TextField(
                blank=True, default="", verbose_name="resolution notes"
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Submitted", "Submitted"),
                    ("Received", "Received"),
                    ("In Progress", "In Progress"),
                    ("On Hold", "On Hold"),
                    ("Completed", "Completed"),
                    ("Rejected", "Rejected"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Submitted",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(fields=["status"], name="maintenance_status_b8d89d_idx"),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["priority"], name="maintenance_priorit_7af9c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["category"], name="maintenance_categor_1e2358_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["requested_by"], name="maintenance_request_0a1373_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(fields=["house"], name="maintenance_house_i_4af79e_idx"),
        ),
        migrations.AddField(
            model_name="maintenancerequestlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequestlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequestlog",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="houses.maintenancerequest",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequestlog",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequestlog",
            index=models.Index(
                fields=["request"], name="maintenance_request_f03c07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequestlog",
            index=models.Index(
                fields=["event_type"], name="maintenance_event_t_7fcba8_idx"
            ),
        ),
    ]
