# Generated by Django 5.1.4 on 2026-08-19 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0005_populate_official_departments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["level"], name="departments_level_002fcb_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["sort_order"], name="departments_sort_or_25235c_idx"
            ),
        ),
    ]
