# Generated by Django 5.1.4 on 2026-08-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0006_department_departments_level_002fcb_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="name"),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("parent", "name")},
        ),
    ]
